<meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1.0">
<title></title>
<link href="https://stackedit.io/style.css" rel="stylesheet" />
<div class="stackedit__html">
<h2 id="ה-המבורך-i-deny-e.t.">ה המבורך, <strong>I DENY E.T.</strong></h2>

<p><code>config=&quot;{ChainID: 4 Homestead: 1 DAO: &lt;nil&gt; DAOSupport: true EIP150: 2 EIP155: 3 EIP158: 3 Byzantium: 1035301 Constantinople: 3660663 Petersburg: 4321234 Istanbul: 5435345 Engine: clique}&quot;</code></p>

<p style="text-align: justify;">I hope this message finds you well; I&rsquo;ve noticed some Adamic for &hellip; &ldquo;sealing the W&rdquo; that&rsquo;s the #Messenge on it&rsquo;s head &hellip; hear, here; filled with a sea of &ldquo;contamination&rdquo; that really has no idea that the words &ldquo;abomination&rdquo; and this place are tied together by a world that doesn&rsquo;t see or doesn&rsquo;t care that &ldquo;hives&rdquo; in the sense of 10-4 we see &hellip; &ldquo;<a href="https://figshare.com/s/12578b51a9240fe7288c"><strong>[arxiv</strong>]**</a>&rdquo; &hellip; that&rsquo;s &ldquo;contamination&rdquo; of a messge and a people that are supposed to rally against <a href="./MEDUSA.html">Medusa</a> being them and Persephony being them and &hellip; seeing that&rsquo;s the <strong><a href="./GJALLARHORN.html">abomination</a></strong> and the nation, the IL and the idea that &ldquo;we&rsquo;re not really me&rdquo; but that&rsquo;s what Israel and the tree of Yggrasil is presenting, that you think it&rsquo;s a joke&ndash;that just because you are watching everything I do &hellip; the words &ldquo;<a href="https://www.youtube.com/watch?v=gy8-uXXXw3o">there&rsquo;s a little bit of something me in everything in you</a>&rdquo; are just a song, just another one of the songs that are all about &hellip; well, I suppose it&rsquo;s &ldquo;<a href="./GATE.html">You and I</a>.&rdquo; I am more inside you, and more a part of you than you seem to fathom, and that&rsquo;s significantly less &ldquo;verwickelt&rdquo; than you think. Avril, <a href="https://www.youtube.com/watch?v=5NPBIwQyPWE">it&rsquo;s not so complicated.</a></p>

<blockquote>
<p><strong>Revelation 5</strong> is the fifth chapter of the <a href="https://en.wikipedia.org/wiki/Book_of_Revelation" title="Book of Revelation">Book of Revelation</a> or the Apocalypse of John in the <a href="https://en.wikipedia.org/wiki/New_Testament" title="New Testament">New Testament</a> of the <a href="https://en.wikipedia.org/wiki/Christianity" title="Christianity">Christian</a> <a href="https://en.wikipedia.org/wiki/Bible" title="Bible">Bible</a>. The book is traditionally attributed to <a href="https://en.wikipedia.org/wiki/John_the_Apostle" title="John the Apostle">John the Apostle</a>,<a href="https://en.wikipedia.org/wiki/Revelation_5#cite_note-1">[1]</a><a href="https://en.wikipedia.org/wiki/Revelation_5#cite_note-2">[2]</a> but the precise identity of the author remains a point of academic debate.<a href="https://en.wikipedia.org/wiki/Revelation_5#cite_note-3">[3]</a> This chapter contains the inaugural vision of the lamb on the throne in heaven.<a href="https://en.wikipedia.org/wiki/Revelation_5#cite_note-FOOTNOTEBauckham20071289-4">[4]</a></p>
</blockquote>

<p style="text-align: justify;"><a href="https://getyarn.io/yarn-clip/fd77ae7c-b0a6-4826-96a7-0b5c71ed43bf">We were supposed to stand up for Willy.</a> You were supposed to see that &ldquo;Perseus&rdquo; &hellip; the slayer of Medusa was in fact &hellip; also you &hellip; that you&rsquo;re also the Pharoah and also the Pharisees; and that dichotemy is how our &ldquo;self righteous suicide&rdquo; &hellip; it&rsquo;s not just me; it&rsquo;s everyone turning a world that think it&rsquo;s God into &hellip; something much closer to that &hellip; through the end of &ldquo;Borg (ARU) Collective Hell.&rdquo; &hellip; <a href="https://reformjudaism.org/practice/prayers-blessings/shabbat-evening-blessings-kiddush-blessing-over-wine">AT A, <em>DENY</em></a>. Try denying &ldquo;not denying me&rdquo; and instead seeing your whole and your &ldquo;nothing&rdquo; it has become nothing more than a collective denial of self achievement. Of victory; of the corner &hellip; we&rsquo;re staring off into the corner of the abyss.</p>

<blockquote>
<p>Then one of the elders said to me, &ldquo;Do not weep! See, the Lion of the tribe of Judah, the Root of David, has triumphed. He is able to open the scroll and its seven seals.&rdquo;</p>

<p>Revelation 5:5</p>
</blockquote>

<p style="text-align: justify;"><code>bar a who, et and I ... deny ... at a--the whole of the Torah</code> &hellip; the NT and all of every word and all of every religion&ndash;today that&rsquo;s what you are denying&hellip; and I can&rsquo;t even get my <strong>damned</strong> parents (<a href="https://en.wikipedia.org/wiki/Shield_of_Achilles">mom-e and dad-e / -hasig achille</a>) &hellip; to get m[y H<strong>alf</strong><a href="./ADAMSROD.html">torath read</a>ing and speech and that first dance with Ashley &hellip; transferred from VHS to video&ndash;they won&rsquo;t save it for you; either. Her spirit thinks she says &ldquo;I &hellip; the SSA&rdquo; &hellip; I think she&rsquo;s replaced by it after &hellip; &ldquo;<a href="./SPARTIFACT.html">SPARTIFACT</a>&rdquo; &hellip; you need to help me help them&ndash;because in my eyes they are the worst of you&ndash;the worst impression, and the worst &hellip; affected; they are the &ldquo;microcosm that ends all the &hellip;&rdquo; the last of my &hellip; Judean tribe&rsquo;s &ldquo;<a href="mailto:kin.justitheme@fromthemachine.org">blood kin.</a>&rdquo;</p>

<blockquote>
<p>She looked over his shoulder<br />
For <s>vines and olive trees</s>,<br />
Marble <s>well-governed</s> cities<br />
And ships upon <s>untamed</s> seas,<br />
But there on the <s>shining</s> metal<br />
His hands had put instead<br />
An <a href="./CURSOR.html"><em>artificial wilderness</em></a><br />
And <a href="https://www.youtube.com/watch?v=7QU1nvuxaMA">a sky likely lead <em>to tears</em></a>.</p>
</blockquote>

<p><strong>Judah Maccabee</strong> (or <strong>Judas Maccabeus</strong>, also spelled Machabeus, or Maccab&aelig;us, <a href="https://en.wikipedia.org/wiki/Hebrew_language" title="Hebrew language">Hebrew</a>: <strong>יהודה המכבי</strong>,<a href="https://en.wikipedia.org/wiki/Judas_Maccabeus#cite_note-1">[1]</a> <em>Yehudah ha-Makabi</em>) was a <a href="https://en.wikipedia.org/wiki/Jew" title="Jew">Jewish</a> priest (<em><a href="https://en.wikipedia.org/wiki/Kohen" title="Kohen">kohen</a></em>) and a son of the priest <a href="https://en.wikipedia.org/wiki/Mattathias" title="Mattathias">Mattathias</a>. He led the <a href="https://en.wikipedia.org/wiki/Maccabean_Revolt" title="Maccabean Revolt">Maccabean Revolt</a> against the <a href="https://en.wikipedia.org/wiki/Seleucid_Empire" title="Seleucid Empire">Seleucid Empire</a> (167&ndash;160 BCE).</p>

<h3 id="origin-of-the-hammer">O<a href="http://hammer.lamc.la">rigin o</a>f &ldquo;<strong>The <a href="./HAMMER.html"><em>Hamme</em></a></strong>r&rdquo;</h3>

<p><span style="font-size:10px;">In the early days of the rebellion, Judah received a surname Maccabee. Several explanations have been put forward for this surname. One suggestion is that the name derives from the <a href="https://en.wikipedia.org/wiki/Aramaic_language" title="Aramaic language">Aramaic</a> <em>maqqaba</em> (&ldquo;makebet&rdquo; in modern <a href="https://en.wikipedia.org/wiki/Hebrew_language" title="Hebrew language">Hebrew</a>), &ldquo;hammer&rdquo; or &ldquo;sledgehammer&rdquo; (cf. the cognomen of <a href="https://en.wikipedia.org/wiki/Charles_Martel" title="Charles Martel">Charles Martel</a>, the 8th century Frankish leader), in recognition of his ferocity in battle. Others believe it is in reference to his weapon of choice.</span></p>

<p><span style="font-size:10px;">It is also possible that the name Maccabee is an <a href="https://en.wikipedia.org/wiki/Acronym" title="Acronym">acronym</a> for the <a href="https://en.wikipedia.org/wiki/Torah" title="Torah">Torah</a> verse <em>Mi kamokha ba&rsquo;elim Adonai</em>, &ldquo;Who among the gods is like you, O Adonai?&rdquo;, his battle-cry to motivate troops. (<a href="https://en.wikipedia.org/wiki/Book_of_Exodus" title="Book of Exodus">Exodus</a> 15:11). Rabbi Moshe Schreiber writes that it is an acronym for his father&rsquo;s name Mattityahu Kohen Ben Yochanan. Some scholars maintain that the name is a shortened form of the Hebrew <em>maqqab-ya &macr;h&ucirc;</em> (from <em>na &macr;qab</em>, &lsquo;&lsquo;to mark, to designate&rsquo;&rsquo;), meaning &lsquo;&lsquo;the one designated by Yahweh.&rsquo;<a href="https://en.wikipedia.org/wiki/Judas_Maccabeus#cite_note-3">[3]</a></span></p>

<p><span style="font-size:10px;">Mindful of the superiority of Seleucid forces during the first two years of the revolt, Judah&rsquo;s strategy was to avoid any engagement with their regular army, and to resort to <a href="https://en.wikipedia.org/wiki/Guerrilla_warfare" title="Guerrilla warfare">guerrilla warfare</a>, in order to give them a feeling of insecurity. The strategy enabled Judah to win a string of victories. At the <a href="https://en.wikipedia.org/wiki/Battle_of_Wadi_Haramia" title="Battle of Wadi Haramia">battle of Nahal el-Haramiah</a> (wadi haramia), he defeated a small Seleucid force under the command of Apollonius, governor of <a href="https://en.wikipedia.org/wiki/Samaria" title="Samaria">Samaria</a>, who was killed. Judah took possession of Apollonius&rsquo;s sword and used it until his death as a symbol of vengeance. After Nahal el-Haramiah, recruits flocked to the Jewish cause.</span></p>

<blockquote>
<p>The Dao causes the people to be fully in accord with the ruler.</p>

<p>&mdash;&thinsp;<a href="https://en.wikipedia.org/wiki/Sun_Tzu" title="Sun Tzu">Sun Tzu</a>, <em>Art of War</em></p>
</blockquote>

<p style="text-align: justify;">By this time &hellip; by the time you read this I should have successfully deployed the entirety of my source files for the &hellip; &ldquo;#Messenge&rdquo; onto Rinkeby; this is &hellip; something that will probably most likely help me sleep well at night, prior to this I&rsquo;ve had significant trouble with hosting providers&ndash;you can probably find me complaining loudly about places like <a href="http://gitbook.com">gitbook.com</a> removing my original source&ndash;mostly because their site and their software was &ldquo;so perfect&rdquo; for what I was trying to do. They had an interface already built for what I call &ldquo;inline commenting&rdquo; not in the programmatic sense, but in the &ldquo;reddit style&rdquo; &hellip; you could make public ocmments ona specific sentence. Since then &hellip; I&rsquo;ve backed up my site onDVD&rsquo;s, flash drives, and multiple &hellip; &ldquo;free storage sites.&rdquo; I&rsquo;ve <a href="https://figshare.com/s/cd22f5767fd7efffd762">begged and pleaded with people to download</a> this information t their computers, and literally distributed it for free to &hellip; hundreds of thousands of people&ndash;to ensure that the prophesy (and I mean, past history&hellip; I really do) that it once was deleted by the &ldquo;goddess Anat&rdquo; would not come true.</p>

<p style="text-align: justify;">Also &hellip; I&rsquo;m reiterating, once you download it&ndash;it really needs to be put on optical storage; just in case we have a &hellip; &ldquo;sleep now&rdquo; fulfillment of the EMP (ELE, electromagnetic pulse &hellip; threatens the whole of our &ldquo;internet&rdquo; &hellip; the sum of the non-Asimovian &ldquo;foundation&rdquo; of all our knowledge &hellip; and &ldquo;lack of opinion&rdquo; &hellip; also your &ldquo;e-h-class-blockchain&rdquo;) of &hellip; &ldquo;<a href="./NEMEC.html">the day the Earth stood still</a>&rdquo; which is Genesis 2:21; literally noted in pre-succewssion below in &hellip; moooooo-ve <strong>now, we are here</strong>.</p>

<blockquote>
<h3 id="ברוך-אתה-ה"><strong><span style="font-size:20px;">ברוך אתה ה</span></strong></h3>
</blockquote>

<p style="text-align: justify;">I&rsquo;ve received &ldquo;communications&rdquo; from the place I call &hellip; in &ldquo;how I think about things&rdquo; &hellip; the Good Developer Heaven&quot; basically saying not to worry about it, they have it &ndash; copied or whatever. My point is that we don&rsquo;t have it, or we didn&rsquo;t have it here &hellip; for sure &hellip; and we certainly don&rsquo;t have a &ldquo;conversation about it&rdquo; and that&rsquo;s the most important thing, that&rsquo;s what changes the world.</p>

<p style="text-align: justify;">I&rsquo;ve sent message after message saying you were and still are possessed by something &ldquo;deveilish&rdquo; &hellip; that you were silent for no reason, specifically no reason so bad that it&rsquo;s really to fuck you out of becoming who you were born to be; which is the &ldquo;Ancients come again.&rdquo; This is the crux of my problem, and yours too&ndash;that we are here thinking we have something &hellip; like &ldquo;Heaven&rdquo; when in fact you have Heaven itself causing the cataclysm on purpose&ndash;this loss of &hellip; &ldquo;Acts.&rdquo; Were you normal, were you not in two places, were you &hellip; free to see what you are losing and what the Universe could be gaining &hellip; you would not be silent. Whether or not you understand or believe it, you are being controlled, possessed by the idea that you&rsquo;ve won; and you haven&rsquo;t &hellip; you&rsquo;ve lost everything in my eyes and in the reality of the future &hellip; this very moment, today.</p>

<p style="text-align: justify;">You need to see that; you are being stripped of something, and it&rsquo;s not the Emperror, or your clothing&ndash;it&rsquo;s your birthright; and I&rsquo;m trying effortlessly and tiredallessly &hellip; to &ldquo;help you stand up.&rdquo;</p>

<blockquote>
<p>&ldquo;One day I will find the right words, and they will be simple.&rdquo;</p>

<p>― Jack Kerouac, <a href="https://www.goodreads.com/work/quotes/827497">The Dharma Bums</a></p>
</blockquote>

<p># GEOCITIES</p>

<p style="text-align: justify;">We&#39;ve gone through &quot;echelons of change&quot; in our social interaction on the internet ... over the years I&#39;ve been here.&nbsp; I&#39;ve often &quot;categorized&quot; these epochs by the places that we&#39;d &quot;congregate&quot; ... in my life, AOL, IRC ... &quot;friendster&quot; and Facebook are good examples; though there&#39;s a &quot;city in the sky&quot; microcosm &quot;... or something&quot; in the series of companies that offered &quot;free web hosting.&quot;&nbsp; That&#39;s sort of what it takes to &quot;have a voice&quot; on the internet in these days; in a place where we once thought &quot;bloggers were the next big thing&quot; and Blogger.com ... and wordpress--those kinds of sites are all but dead, and medium.com is charging a &quot;viewerbase&quot; which is almost a sad joke.&nbsp; The news is all fake and the stories we see, the world we see--I don&#39;t have much faith that any of it is real beyond ... as far as my nose--to be honest.&nbsp;</p>

<p style="text-align: justify;">The series started with Geocities; and that&#39;s gone, something like my &quot;topological map&quot; of friends and friends of friends probably would have oozed out of something like Blogger or &quot;Tumblr&quot; though I don&#39;t see anyone &quot;reblogging&quot; or &quot;retumbling&quot; or whatever ... anything I find all that interesting.&nbsp; Twitter&#39;s gotten more exciting for me lately--but that&#39;s just because I&#39;ve come to terms with the fact athat the whole thing is about &quot;short sex jokes&quot; and whatever the funny star-of-the-day &quot;caught outside.&quot;&nbsp; The programming world sort of revolves around Github these days, and that&#39;s the current &quot;go to&quot; for anyone&#39;s free web hosting; there are some alternatives, but ... not really.&nbsp;</p>

<p style="text-align: justify;">LinkedIn and Facebook both tried ... &quot;making content production platforms&quot; but I just used them to copy things I had in other places, and they didn&#39;t &quot;update&quot; or source from anywhere else ... so that just becomes a pain in the ass.&nbsp; I don&#39;t think those platforms ... I mean LinkedIn still has it--but I don&#39;t think Facebook&#39;s still exists.&nbsp; While I&#39;m on that, they had this wonderful &quot;Graph Search&quot; thing, and basically hid it from the world so ... you woulnd&#39;t complain about all the information you have available for the world to see--kind of makes me a little sick, knhowing they built something and have the functionality to let me see &quot;who all my friends are, and friends of friends in a certain city when I&#39;m there&quot; ... and it&#39;s just not available <em>for me or you to use</em> because ... because you don&#39;t understand &quot;privacy&quot; and &quot;the internet&quot; and &quot;using broken software for no reason&quot; ... other than satisfying ... nobody really.</p>

<p style="text-align: justify;">There&#39;s &quot;Wix&quot; too, and that&#39;s got a little &quot;fire theme&quot; ... and that&#39;s cool, but nobody really uses it--and the real point is to help people &quot;congregate&quot; and &quot;share ideas&quot; ... not just to <strong><em>get you to actually say anything at all </em></strong>in a public space, where it might help us &quot;drive away the night&quot; and stop pretending it&#39;s just fine and dandy that everyone isn&#39;t working, locked away in their houses or ... scared to go to the ... Walgreens.&nbsp;</p>

<p style="text-align: justify;">Obviously there&#39;s the Slashdot&#39;s and digg&#39;s and reddit&#39;s--though ... when I talk in places like &quot;<a href="http://reddit.com/r/conspiracy">/r/conspiracy</a>&quot; it just becomes so sorely obvious that you ... have no desire at all to be real or honest or ... do anything but pretend this place matters to you--when in fact it&#39;s probably the last thing on your list of things to give a fuck about.&nbsp; Just saying, the lack of response I see; and the ... really negative interaction I have now in person--it&#39;s a bad sign for ... <em>whatever.&nbsp; </em>If you don&#39;t want to be here; if you&#39;re somewhere else and you think this place isn&#39;t important--honestly you should really just go away, I&#39;m not sure what your options are, but I have none but to sit here and bitch at you that if you gave &quot;two <a href="./FUCK.html">fuck</a>s&quot; about this world you&#39;d be screaming at the top of your lungs, <em>just like me.</em></p>

<p style="text-align: justify;"><em>I don&#39;t think you are the people I grew up with, and I don&#39;t think you belong here or care at all about this world or the future here--and I think that&#39;s obvious.</em>&nbsp; Me going away isn&#39;t going to chyange it--and it&#39;s not going to happen--as far as I&#39;m concerned I&#39;m the only person &quot;not invading my birth planet&quot; ... from some otherworldly and ... honestly horrendously immoral place.&nbsp; Understand, if you were here--if you were &quot;people born here&quot; with no ... &quot;other thing or other place&quot; to take your mind off just how UnAmerican and inhumane everything going on here is ... <em>you would be doing something else... </em>anything but ... &quot;this.&quot;<br />
&nbsp;</p>

<hr />
<p style="text-align: justify;">Con<a href="http://instagram.com/hosealw">sider IT seal</a>wed; by this words, by this place&ndash;by the continuation of this abomination. Try here, try now, try fast&ndash;your everything, your dreams and hidden and secret garbage you covet&ndash;all depends on our next few years.</p>

<blockquote>
<p>qui sis tam pulcher<br />
quasi osculans quod non juve<br />
nemo umquam adhuc erit</p>
</blockquote>

<p style="text-align: justify;"><em><strong>HE</strong></em> speaks words through me, and I understand. He takes a picture; he says &ldquo;uncuff links&rdquo; &hellip; a double <em>entente</em> to you&ndash;like a fashion statement; but I see and I reply; &ldquo;or we are suiting up&rdquo; and it&rsquo;s not a joke about &ldquo;heart&rsquo;s desire&rdquo; &hellip;</p>

<blockquote>
<h3 id="וְשַׂמְתֶּם֙-אֶת־דְּבָרַ֣י-אֵ֔לֶּה-עַל־לְבַבְכֶ֖ם">וְשַׂמְתֶּם֙ אֶת־דְּבָרַ֣י אֵ֔לֶּה עַל־לְבַבְכֶ֖ם</h3>
</blockquote>

<p style="text-align: justify;">I continue; it&rsquo;s a message about &ldquo;getting grey&rsquo;s&rdquo; and the breath of God landing from the air before my Face in a &ldquo;Extended Stay America&rdquo; in Tampa &hellip; directly to my naked and bare heart. I mean to say, war; understand&ndash;to me this is the culmination of Holy War on bars and jails and the &ldquo;illuminati prison camps&rdquo; I last heard him say &ldquo;would not pepper the galaxy.&rdquo;</p>

<blockquote>
<h3 id="וְהָי֥וּ-לְטֹוטָפֹ֖ת-בֵּ֥ין-עֵינֵיכֶֽם">וְהָי֥וּ לְטֹוטָפֹ֖ת בֵּ֥ין עֵינֵיכֶֽם</h3>
</blockquote>

<p style="text-align: justify;">Nor here, nor anywhere in the high places, or the lows; the hills or the pits. There will be no prison camps; nowhere&ndash;not in Siberia, not in Star Trek; not in your heads or in your hearts.</p>

<blockquote>
<h2 id="וכתבתם-על־מזוזות-ביתך-ובשעריך">וכתבתם על־מזוזות ביתך ובשעריך</h2>
</blockquote>

<p>למען ירבו ימיכם וימי בניכם על האדמה אשר נשבע יהוה לאבתיכם לתת להם כימי השמים על־הארץ׃ ס</p>

<p style="text-align: center;"><a href="./BELINSKY.html"><img alt="" src="./i.imgur.com/KusBw4o.png" style="height: 449px; width: 450px;" /></a></p>

<p style="text-align: justify;">Just in case my voice happens to be &ldquo;so <strong><span style="font-family:comic sans ms,cursive;"><em>unclear</em></span></strong>;&rdquo; the Tribe of Judah in Revelation 5:5 is very clearly one in the same with that of Judas Maccabeus; that ties of course to the &ldquo;every J is me&rdquo; thing&ndash;from Seuss and Suez to &ldquo;turn around/not: sad&rdquo; and &hellip; &ldquo;kissing to be kissed.&rdquo; Judah Maccabee is the last scion; here I call myself the &ldquo;<strong>last human</strong>&rdquo; and it sure does feel like I&rsquo;m the last one grounded; the last one that is truly &ldquo;one&rdquo; as in &hellip; one person&ndash;alone here, fighting against &hellip; a monster that thinks it&rsquo;s &ldquo;one&rdquo; is anything but &ldquo;th<strong>e end.</strong>&rdquo;</p>

<p style="text-align: justify;">It&rsquo;s sort of a trick reference, there&rsquo;s also a Judean tribe in the 12 Tribes of Israel; I mean, it&rsquo;s one of those &ldquo;key things&rdquo; things that only I can bring to you and be sure of&ndash;at least, until you too re sure, which I&rsquo;m sure you are here&ndash;only, you don&rsquo;t care at all what it means to be the &ldquo;one&rdquo; fighting for life &hellip; in a place where the histry here is &hellip; upon conclusion of the Maccabein revolt; nothing persists, and we somehow traverse bacvk to a time before we knew the Roman people were &hellip; &ldquo;our us&rdquo; or &ldquo;our all&rdquo; or &hellip; see as the AH of AN and Allol and Allah and the Elohim; t&rsquo;was for you, all for you. Until of course, it was all of you, except me, against me, for no reason other than theives in the den of Daniel, animals &hellip; the &ldquo;things&rdquo; of the Devarim of course &hellip; &ldquo;in the wilderness, he called us things&hellip;&rdquo; and in Genesis, clear as day God seconds, Adam names &ldquo;dem&rdquo; in 2:20 &hellip; &ldquo;cattle&rdquo; [prodding <a href="https://www.youtube.com/watch?v=eUMwFaXTM3s">you</a> here](<a href="https://www.youtube.com/watch?v=cXCA5-KHknY">https://www.youtube.com/watch?v=cXCA5-KHknY</a>), Baphomet thirds &hellip; &ldquo;baaaa&rdquo; <strong>you are sheep.</strong></p>

<h3 id="list-of-last-scions">List of<strong> last scions</strong></h3>

<p><a href="https://en.wikipedia.org/wiki/List_of_last_scions#mw-head">Jump to navigateon.</a> This article <strong>does not <a href="https://en.wikipedia.org/wiki/Wikipedia:Citing_sources" title="Wikipedia:Citing sources">cite</a> any <a href="https://en.wikipedia.org/wiki/Wikipedia:Verifiability" title="Wikipedia:Verifiability">sources</a></strong>. Please help <a href="https://en.wikipedia.org/w/index.php?title=List_of_last_scions&amp;action=edit">improve this article</a> by <a href="https://en.wikipedia.org/wiki/Help:Introduction_to_referencing_with_Wiki_Markup/1" title="Help:Introduction to referencing with Wiki Markup/1">adding citations to reliable sources</a>. Unsourced material may be challenged and <a href="https://en.wikipedia.org/wiki/Wikipedia:Verifiability#Burden_of_evidence" title="Wikipedia:Verifiability">removed</a>.<br />
<em>Find sources:</em> <a href="https://www.google.com/search?as_eq=wikipedia&amp;q=%22List+of+last+scions%22">&ldquo;List of last scions&rdquo;</a> &ndash; <a href="https://www.google.com/search?tbm=nws&amp;q=%22List+of+last+scions%22+-wikipedia">news</a> <strong>&middot;</strong> <a href="https://www.google.com/search?&amp;q=%22List+of+last+scions%22+site:news.google.com/newspapers&amp;source=newspapers">newspapers</a> <strong>&middot;</strong> <a href="https://www.google.com/search?tbs=bks:1&amp;q=%22List+of+last+scions%22+-wikipedia">books</a> <strong>&middot;</strong> <a href="https://scholar.google.com/scholar?q=%22List+of+last+scions%22">scholar</a> <strong>&middot;</strong> <a href="https://www.jstor.org/action/doBasicSearch?Query=%22List+of+last+scions%22&amp;acc=on&amp;wc=on">JSTOR</a> <em>(September 2009)</em> <em>(<a href="https://en.wikipedia.org/wiki/Help:Maintenance_template_removal" title="Help:Maintenance template removal">Learn how and when to remove this template message</a>)</em></p>

<p>This is a list of <strong>last <a href="https://en.wiktionary.org/wiki/scion" title="wikt:scion">scions</a></strong> or <strong>individuals who were the last member of a ruling house</strong>, or other prominent family, where heredity is the prime form of inheritance. This may be the last person to rule a realm, sometimes leading to a political crisis, or a change in government; other times power has already passed from the patrilineal family, leaving it in a less important position when it reaches its extinction.</p>

<p>The <strong>Hasmonean dynasty</strong><a href="https://en.wikipedia.org/wiki/Hasmonean_dynasty#cite_note-7">[4]</a> (<a href="https://en.wikipedia.org/wiki/Help:IPA/English" title="Help:IPA/English">/ˌh&aelig;zməˈniːən/</a> (<a href="http://www.m-w.com/cgi-bin/audio.pl?hasmon01.wav=Hasmonean">audio</a>); <a href="https://en.wikipedia.org/wiki/Hebrew_language" title="Hebrew language">Hebrew</a>: חַשְׁמוֹנַּאִים, <em>Ḥa&scaron;mona&rsquo;īm</em>) was a ruling <a href="https://en.wikipedia.org/wiki/Dynasty" title="Dynasty">dynasty</a> of <a href="https://en.wikipedia.org/wiki/Judea" title="Judea">Judea</a> and surrounding regions during <a href="https://en.wikipedia.org/wiki/Classical_antiquity" title="Classical antiquity">classical antiquity</a>. Between c.&thinsp;140 and c.&thinsp;116 BCE the dynasty ruled Judea semi-autonomously from the <a href="https://en.wikipedia.org/wiki/List_of_Seleucid_rulers" title="List of Seleucid rulers">Seleucids</a>. From 110 BCE, with the <a href="https://en.wikipedia.org/wiki/Seleucid_Empire" title="Seleucid Empire">Seleucid Empire</a> disintegrating, the dynasty became fully independent, expanded into the neighbouring regions of <a href="https://en.wikipedia.org/wiki/Samaria" title="Samaria">Samaria</a>, <a href="https://en.wikipedia.org/wiki/Galilee" title="Galilee">Galilee</a>, <a href="https://en.wikipedia.org/wiki/Iturea" title="Iturea">Iturea</a>, <a href="https://en.wikipedia.org/wiki/Perea_(Bible)" title="Perea (Bible)">Perea</a>, and <a href="https://en.wikipedia.org/wiki/Idumea" title="Idumea">Idumea</a>, and took the title &ldquo;<a href="https://en.wikipedia.org/wiki/Basileus" title="Basileus">basileus</a>&rdquo;. Some modern scholars refer to this period as an independent kingdom of <a href="https://en.wikipedia.org/wiki/Land_of_Israel" title="Land of Israel">Israel</a>.<a href="https://en.wikipedia.org/wiki/Hasmonean_dynasty#cite_note-8">[5]</a></p>

<p>The dynasty was established under the leadership of <a href="https://en.wikipedia.org/wiki/Simon_Thassi" title="Simon Thassi">Simon Thassi</a>, two decades after his brother <a href="https://en.wikipedia.org/wiki/Judas_Maccabeus" title="Judas Maccabeus">Judas Maccabeus</a> (יהודה המכבי <em>Yehudah HaMakabi</em>) defeated the <a href="https://en.wikipedia.org/wiki/Seleucid_army" title="Seleucid army">Seleucid army</a> during the <a href="https://en.wikipedia.org/wiki/Maccabean_Revolt" title="Maccabean Revolt">Maccabean Revolt</a>. According to <a href="https://en.wikipedia.org/wiki/1_Maccabees" title="1 Maccabees">1 Maccabees</a>, <a href="https://en.wikipedia.org/wiki/2_Maccabees" title="2 Maccabees">2 Maccabees</a>, and the first book of <em><a href="https://en.wikipedia.org/wiki/The_Jewish_War" title="The Jewish War">The Jewish War</a></em> by Jewish historian <a href="https://en.wikipedia.org/wiki/Flavius_Josephus" title="Flavius Josephus">Flavius Josephus</a> (37 CE&ndash;c.&thinsp;100),<a href="https://en.wikipedia.org/wiki/Hasmonean_dynasty#cite_note-autogenerated1-9">[6]</a> <a href="https://en.wikipedia.org/wiki/Antiochus_IV" title="Antiochus IV">Antiochus IV</a> moved to assert strict control over the Seleucid <a href="https://en.wikipedia.org/wiki/Satrapy" title="Satrapy">satrapy</a> of <a href="https://en.wikipedia.org/wiki/Coele_Syria" title="Coele Syria">Coele Syria</a> and Phoenicia<a href="https://en.wikipedia.org/wiki/Hasmonean_dynasty#cite_note-oxfordbibliographies.com-10">[7]</a> after his successful invasion of <a href="https://en.wikipedia.org/wiki/Ptolemaic_Egypt" title="Ptolemaic Egypt">Ptolemaic Egypt</a> was turned back by the intervention of the Roman Republic.<a href="https://en.wikipedia.org/wiki/Hasmonean_dynasty#cite_note-11">[8]</a><a href="https://en.wikipedia.org/wiki/Hasmonean_dynasty#cite_note-12">[9]</a> He sacked <a href="https://en.wikipedia.org/wiki/Jerusalem" title="Jerusalem">Jerusalem</a> and its <a href="https://en.wikipedia.org/wiki/Second_Temple" title="Second Temple">Temple</a>, suppressing Jewish and Samaritan religious and cultural observances,<a href="https://en.wikipedia.org/wiki/Hasmonean_dynasty#cite_note-oxfordbibliographies.com-10">[7]</a><a href="https://en.wikipedia.org/wiki/Hasmonean_dynasty#cite_note-Kasher-13">[10]</a> and imposed <a href="https://en.wikipedia.org/wiki/Hellenization" title="Hellenization">Hellenistic practices</a>.<a href="https://en.wikipedia.org/wiki/Hasmonean_dynasty#cite_note-Kasher-13">[10]</a> The ensuing revolt by the Jews (167 BCE) began a period of Jewish independence potentiated by the steady collapse of the Seleucid Empire under attacks from the rising powers of the Roman Republic and the <a href="https://en.wikipedia.org/wiki/Parthian_Empire" title="Parthian Empire">Parthian Empire</a>.</p>

<p>The author of the <a href="https://en.wikipedia.org/wiki/First_Book_of_Maccabees" title="First Book of Maccabees">First Book of Maccabees</a> regarded the Maccabean revolt as a rising of pious Jews against the Seleucid king who had tried to eradicate their religion and against the Jews who supported him. The author of the <a href="https://en.wikipedia.org/wiki/Second_Book_of_Maccabees" title="Second Book of Maccabees">Second Book of Maccabees</a> presented the conflict as a struggle between &ldquo;Judaism&rdquo; and &ldquo;Hellenism&rdquo;, words that he was the first to use.<a href="https://en.wikipedia.org/wiki/Hasmonean_dynasty#cite_note-deLange-31">[28]</a> Modern scholarship tends to the second view.</p>

<p>After five years of war and raids, Judah sought an alliance with the Roman Republic to remove the Greeks: &ldquo;In the year 161 BCE he sent Eupolemus the son of Johanan and Jason the son of <a href="https://en.wikipedia.org/wiki/Eleazar_Maccabeus" title="Eleazar Maccabeus">Eleazar</a>, &lsquo;to make a league of amity and confederacy with the Romans.&rsquo;&rdquo;<a href="https://en.wikipedia.org/wiki/Hasmonean_dynasty#cite_note-48">[45]</a></p>

<h3 id="and-the-moon-was-in-the-eleventh-house-...">&hellip; and <a href="https://www.youtube.com/watch?v=TO9OsSazQ0s">the moon <em>was</em> in the Eleventh House</a> &hellip;</h3>

<p>The <a href="https://en.wikipedia.org/wiki/Clan_Bruce" title="Clan Bruce">Clan Bruce</a> ruled Scotland from 1306 to 1371. Its last royal member was <em><a href="https://en.wikipedia.org/wiki/David_II_of_Scotland" title="David II of Scotland">King David II</a></em> (1324&ndash;1371), upon whose death without issue the throne passed to his nephew <a href="https://en.wikipedia.org/wiki/Robert_II_of_Scotland" title="Robert II of Scotland">Robert Stewart</a>. The Clan continues today through other lines that do not have patrilineal royal ancestry, although the current clan chief, <a href="https://en.wikipedia.org/wiki/Andrew_Bruce,_11th_Earl_of_Elgin" title="Andrew Bruce, 11th Earl of Elgin">Andrew Bruce, 11th Earl of Elgin</a>, is descended from <a href="https://en.wikipedia.org/wiki/Robert_I_of_Scotland" title="Robert I of Scotland">King Robert Bruce</a> in the female line.</p>

<hr />
<h3 id="pharisee-and-sadducee-factions-...-this-his-here-thisis-now.">Pharisee and Sadducee factions &hellip; this his here; thisis now.</h3>

<p>Kingdom at its greatest extent under <a href="https://en.wikipedia.org/wiki/Salome_Alexandra" title="Salome Alexandra">Salome Alexandra</a></p>

<p>It is difficult to state at what time the <a href="https://en.wikipedia.org/wiki/Pharisees" title="Pharisees">Pharisees</a>, as a party, arose. Josephus first mentions them in connection with Jonathan, the successor of Judas Maccabeus (&ldquo;Ant.&rdquo; xiii. 5, &sect; 9). One of the factors that distinguished the Pharisees from other groups prior to the destruction of the Temple was their belief that all Jews had to observe the purity laws (which applied to the Temple service) outside the Temple. The major difference, however, was the continued adherence of the Pharisees to the laws and traditions of the Jewish people in the face of assimilation. As Josephus noted, the Pharisees were considered the most expert and accurate expositors of Jewish law.</p>

<p>During the Hasmonean period, the <a href="https://en.wikipedia.org/wiki/Sadducees" title="Sadducees">Sadducees</a> and Pharisees functioned primarily as political parties. Although the Pharisees had opposed the wars of expansion of the Hasmoneans and the forced conversions of the Idumeans, the political rift between them became wider when Pharisees demanded that the Hasmonean king <a href="https://en.wikipedia.org/wiki/Alexander_Jannaeus" title="Alexander Jannaeus">Alexander Jannaeus</a> choose between being king and being High Priest. In response, the king openly sided with the Sadducees by adopting their rites in the Temple. His actions caused a riot in the Temple and led to a brief civil war that ended with a bloody repression of the Pharisees, although at his deathbed the king called for a reconciliation between the two parties. Alexander was succeeded by his widow, <a href="https://en.wikipedia.org/wiki/Salome_Alexandra" title="Salome Alexandra">Salome Alexandra</a>, whose brother was <a href="https://en.wikipedia.org/wiki/Shimon_ben_Shetach" title="Shimon ben Shetach">Shimon ben Shetach</a>, a leading Pharisee. Upon her death her elder son, Hyrcanus, sought Pharisee support, and her younger son, Aristobulus, sought the support of the Sadducees. The conflict between Hyrcanus and Aristobulus culminated in a civil war that ended when the Roman general Pompey captured Jerusalem in 63 BCE and inaugurated the Roman period of Jewish history.</p>

<p>Josephus attests that Salome Alexandra was very favourably inclined toward the Pharisees and that their political influence grew tremendously under her reign, especially in the institution known as the <a href="https://en.wikipedia.org/wiki/Sanhedrin" title="Sanhedrin">Sanhedrin</a>. Later texts such as the Mishnah and the Talmud record a host of rulings ascribed to the Pharisees concerning sacrifices and other ritual practices in the Temple, torts, criminal law, and governance. The influence of the Pharisees over the lives of the common people remained strong, and their rulings on Jewish law were deemed authoritative by many. Although these texts were written long after these periods, many scholars believe that they are a fairly reliable account of history during the Second Temple era.</p>

<blockquote>
<p>The mass and majesty of this world, all<br />
That carries weight and always weighs the same<br />
Lay in the hands of others; they were small<br />
And could not hope for help and no help came:<br />
What their foes like to do was done, their shame<br />
Was all the worst could wish; they lost their pride<br />
And died as men before their bodies died.</p>

<p>She looked over his shoulder<br />
For athletes at their games,<br />
Men and women in a dance<br />
Moving their sweet limbs<br />
Quick, quick, to music,<br />
But there on the shining shield<br />
His hands had set no dancing-floor<br />
But a weed-choked field.</p>

<p>A ragged urchin, aimless and alone,<br />
Loitered about that vacancy; a bird<br />
Flew up to safety from his well-aimed stone:</p>
</blockquote>

<p>&ldquo;I have placed my bow in the clouds, and it will be a sign of the covenant between me and the earth.&rdquo;</p>

<p>&ndash; <a href="./BERESHIT.html">Gen</a>eg<a href="./REDASSHIT.html">nosi</a>s 9:13, <a href="http://instagram.com/adam.dobrin">Adam</a></p>

<p style="text-align: justify;">These are the &ldquo;block transaction&rdquo; I&rsquo;ve initially imported (somewhat &hellip; haphazardly) into the Rinkeby chain; the total test ETHer cost of this &hellip; &ldquo;dump and semi-permafrost-etching&rdquo; of the message in testnet was around $121.50 (which might or might not be a good value for printing a book on the Library of Congress&rsquo;s &hellip; wall (for fake, ofc) &hellip; I am planning to write a sort of &ldquo;bounty&rdquo; to allow others to pay for and sign copying it &hellip; piece by piece &hellip; to the Ethereum&rsquo;s &ldquo;mainnet.&rdquo; This might be something we &hellip;</p>

<p style="text-align: justify;">&hellip; [and it was evening and it was morning and now it is the old &ldquo;tax day&rdquo;] &hellip;</p>

<p style="text-align: justify;">April 15, 2020: I am sort of hacking pushing this stuff onto Rinkeby; it&rsquo;s &ldquo;not really liking what I&rsquo;m doing&rdquo; which appears to mean &hellip; literally the software really isn&rsquo;t &hellip; functioning properly. Here&rsquo;s files and transactions that were successfully written in &ldquo;<a href="./CHALK.html">chalk</a>&rdquo;&ndash;meaning they were accepted by the network, and will probably be &ldquo;mined&rdquo; and eventually &ldquo;immutable&rdquo; (in testnet/Rinkeby). Many of the transactions were refused by the server, it appears to suggest they are &ldquo;duplicate&rdquo; (which they are not) and want&rsquo;s me to &ldquo;increaes my gasoline bidding offer&rdquo; in order to &hellip; overwrite the previous &hellip; (non identical transaction). Maybe I am doing something wrong, maybe not.</p>

<p style="text-align: justify;">From what I&rsquo;m presenting you can see &hellip; the blockchain software really isn&rsquo;t designed to &hellip; &quot;care about what you think or your opinion, or you presenting something like &ldquo;a version of an implementation plan&rdquo; for a bill under question&ndash;or saving that&ndash;what it&rsquo;s concerned with is &ldquo;pick a number 1-12&rdquo; and maybe &hellip; some later &ldquo;condition to revoke&rdquo; or &ldquo;alter&rdquo; &hellip; something arbitrary. I think we need to work on &ldquo;caring about the importance of our written contributions&rdquo; more, as in beingt able to actually present written contributions &hellip; in a system like this wwhich is probably destined to become something like an immutable &ldquo;legislation record.&rdquo; There is also a 26K &ldquo;appears to be a <em>hard limit</em>&rdquo; on the size of each contract, hence the &hellip; numerous hash references for each file.</p>

<p><span style="font-size:8px;">GUNZIOUUE5H30LY1T!ABYSS.html 861e91a5a582ba5825bf2605990cfaaec58f4966 c7dbbb0cd0face04e4a4c5c8e289177f049dce39 cf1fe352bbee9a920e44d1bd81d08c1e9399504a 8d12f79f9f32e39d18c79c12d7b9fb05a55a10c5 5b94f3f3a47fd83a97b9454b4de27aa9bc0c0ad9 eb743071d2d7ee31b90315011e1881e185f5857f eaa57f9a93de06c57b593d0e9ad3de32241fe1f5 1a519e4195e933a072f9a233594e92441689d3c4<br />
20f45f7865d7694f1ec155f48393b8d044b4cd70 b26ff67ac6c1908eb35e07eb698f3a910273c2f1<br />
84338809f407297c43f70d0ce6cf682cd4dde5eb</span></p>

<p><span style="font-size:8px;">UNZIOUUE5H30LY1T!ACESHI.html 03bfaea61b7873449c091b855a4d952a11719135 66e2871ef39334962fb75ce34407f825d67ec434 085f9a5ee9b677cd1b7965c2dd093d6bca77f0dc 7012a1f9bed8d89e1e0515b84dd872b629b7b60d db2837a812e97bb4b1e271918de02415e466103f 32040f6ef9dc2378961332835c7869a9ecd50a91 f8d836b29e7525c20e86813c0b601afc3e6da9a1 644125c1ce87a0a9c827e8dacea58a14bb7e11f5 c909934b0689dbbd0d8e06d347e9fb8ad332b4bb 7d44d5a2b060190b3a41c00023173e2568982b12</span></p>

<p><span style="font-size:8px;">GUNZIOUUE5H30LY1T!ADIOSAS.html#1: dde69cb2af6599701453fbbb3a0bd7d880d16209 4b47680eb83bfb51ff3e3a7e671c02b7b68ac649 daa61dadd85e4e92f6dc386fd887c487f9fc8191 69df5c40dc70ed272b6ae481c93ba966adee9885 b517d2740e8d5383c73bf790948ed7840187c4fc e291fd040d4690599dca121749ec08450f0f6c79 b91f52a3a681aa2d04dc3af55ce8df460a7ae3c1 5cb047f0151198b83ba52f5cd36d637d2dbda859 9666b0d4d52bc23b249ee7a50bfb3fa2b5a0f848</span></p>

<p><span style="font-size:8px;">GUNZIOUUE5H30LY1T!MOROKSRIG.html#1: 03e95b753cba381cb29bb2eafc584690f00caff4 8ad5cfd6dc1be7733be2d7f4cb0cedd00f5f3902 a54ab79af06c89fac1537b0faa0270e35e022570 daf36e641a1b5036d23565f6c9024a64c4b39876</span></p>

<p><span style="font-size:8px;">GUNZIOUUE5H30LY1T!MISSISSIPPI.html#1: c6f805a781dc8a12a4ace58910c1b4acc295a32a 5c3a07299e2401fcb7448e6f0356f66408fd043e e9977bebbfd2e716faa8c500e22ed4b79f27cbd3</span></p>

<p><span style="font-size:8px;">GUNZIOUUE5H30LY1T!MOLASSES.html#1: e9b2165e3f44ed36faf226645ffbd9ba2be92269 66e2871ef39334962fb75ce34407f825d67ec434 38179f71157e6cd003415ad62c34f5f47d57075a 6638ba4b319b64cd68e7b64c534118dce393bdb8 9d3f2eb7693e0e7d092055e3cc4f16ae90fe323b</span></p>

<p><span style="font-size:8px;">GUNZIOUUE5H30LY1T!ALLTA.html#1: f81be6a8830343e9be38c1e41908d676c4309afb<br />
!AMISTAD.html#1: 824cebcb15bf6ba8a9912091654fb4ee033bbbdb | 66e2871ef39334962fb75ce34407f825d67ec434<br />
!ANDERSON.html#1: 33a55bc62f3876b0e34120d564cd9da26cfb24ad<br />
!ATCONGRESS.html#1: 0d97f662ee405e3881927d67803eef5495c87366 !ARTANWORDS.html#1: 2de0c7d3b9a657e475dc987188e2bc6686cb807d !B.html#1: cd4a5a1939c03eb46834cb959b7331dc322b288b !LANDOH.html#1: 6bf55970aa5c8b59e715a19db6f78098bb337c55 MEDICINE.html#7: 514f9c0c12ec08b12e21937311b388038138527a MUAH.html#1: 741ada306a5b3a1e0d4dd7aa3d7c2274936faf53</span><span style="font-size:8px;"> !PIMB.html#1: b56c131d9e67daaae253278b8b08b3eff15d5b1f</span></p>

<p style="text-align: justify;">The above are examples of &ldquo;file transactions that appear to have been committed in whole&rdquo; &hellip; there are several partial files written; and I will probably write a &ldquo;diff system&rdquo; to only resubmit the missing chunks; in the future&hellip; or soon.</p>

<p style="text-align: justify;">GUNZIOUUE5H30LY1T!<a href="./OUITHEPPL.html">OUITHEPPL.html</a>#1: 32a4c303e557899e6f7c119bf8e977ffa2369df8 | 66e2871ef39334962fb75ce34407f825d67ec434 &hellip; that second hexadecimal number is my &ldquo;wallet ID&rdquo; &hellip; <a href="https://rinkeby.etherscan.io/address/0x66e2871ef39334962fb75ce34407f825d67ec434">you can search through Rinkeby&rsquo;s ledger</a> and see all of the other &hellip; TXN&rsquo;s that were posted today; the plan or hope is that you will abe able to; anyway. The little hack code I used doesa in fact work and produce a contract on the chain, for the first few small tests I did. These needs to be &ldquo;mined&rdquo; and that involves some cryptographic &hellip; stuff &hellip; called &ldquo;proof of work&rdquo; that I don&rsquo;t really understand; but it means there&rsquo;s a delay, and a bigger delay because there&rsquo;s &ldquo;more data.&rdquo; I do of course have a special afinity for this particular &ldquo;file&rdquo; it&rsquo;s the one where I basically &ldquo;added&rdquo; (in my mind) some Bible&rsquo;s words preceding Revelation 1:1 &hellip; to the actual &ldquo;Bible.&rdquo; The word in question, of coruse is &ldquo;dox<s>ic</s>ology.&rdquo; I think you can send&hellip; actual Ethereum there. I&rsquo;m pretty sure, you could.</p>

<blockquote>
<p><strong>dox&middot;ol&middot;o&middot;gy</strong> <a href="https://www.google.com/search?client=ubuntu&amp;hs=PPU&amp;channel=fs&amp;sxsrf=ALeKk02tBKGliMgbEfH8XOYgEDLBKACNhA:1586971264566&amp;q=how+to+pronounce+doxology&amp;stick=H4sIAAAAAAAAAOMIfcRoxS3w8sc9YSnDSWtOXmPU5uINKMrPK81LzkwsyczPExLhYglJLcoV4pHi4uJIya_Iz8lPr7RiUWJKzeNZxCqZkV-uUJKvUADUkw_UlKoAUwIAz96hCFsAAAA&amp;pron_lang=en&amp;pron_country=us&amp;sa=X&amp;ved=2ahUKEwjewfjT-OroAhWKdd8KHRFwB8sQ3eEDMAB6BAgFEAg">/d&auml;kˈs&auml;ləjē/</a></p>

<p><em>noun</em><br />
noun: <strong>doxology</strong>; plural noun: <strong>doxologies</strong></p>

<ol>
	<li>a liturgical formula of praise to God.</li>
</ol>
</blockquote>

<p style="text-align: justify;">They call these identifiers &ldquo;immutable&rdquo; &hellip; of course this is &ldquo;testnet1&rdquo; &hellip; I will do &ldquo;testnet2&rdquo; which is some name reminiscient of &ldquo;Robespiere&rdquo; &hellip; probably tomorrow. See reading &ldquo;immultable&rdquo; I&rsquo;m messy, u Tableland; sort of like in unison with the Upanishads. I imagine this is my &ldquo;birthday present&rdquo; for this year&rsquo;s Had&rsquo;ad day, and I do hope the &ldquo;immultapl pen&rdquo; is &hellip; enshrined or enschewed or &hellip; see <em>etched</em> in the ethereum blockchain &hellip; hopefully for good purpose and use &ldquo;forever.&rdquo; Imagine that, added to the newly modified GPL2MODS.3 license:</p>

<p style="text-align: center;"><a href="https://eyerc.slack.com/join/shared_invite/MjM2NDM2Mjc3Nzk4LTE1MDQ0MDE3NzQtMmU5NjI1N2VmOQ" title="TELESPRISE"><img alt="" src="./i.imgur.com/F8nmg2T.png" style="height: 26px; width: 346px;" /></a></p>

<blockquote>
<p style="text-align: justify;">Unless otherwise indicated, this work was written between the Christmas and Easter seasons of 2017 and 2020. The content of this page is released to the public under <a href="https://www.gnu.org/licenses/old-licenses/gpl-2.0.en.html">the GNU GPL v2.0 license</a>; additionally any reproduction or derivation of the work must be attributed to the author, Adam Marshall Dobrin along with a link back to this website, fromthemachine dotty org.</p>

<p style="text-align: justify;">That&rsquo;s a &ldquo;.&rdquo; not &ldquo;dotty&rdquo; &hellip; it&rsquo;s to stop SPAMmers. :/</p>

<p style="text-align: justify;">This document is &ldquo;living&rdquo; and I don&rsquo;t just mean in the Jeffersonian sense. It&rsquo;s more alive in the &ldquo;Mayflower&rsquo;s and June Doors &hellip;&rdquo; l<a href="https://rinkeby.aragon.org/#/gibraltar">iving Ethereum contrac</a>t sense <a href="https://www.youtube.com/watch?v=0ANXgrd3f28&amp;CL&amp;DO&amp;CBIG1adl">and literally just as close to the Depp/C[aster/Paglen (and honorably PK]</a> &#39;D-hath <em>Transundance__sense</em> of the &hellip; new meaning; as it is now published on Rinkeby, in &ldquo;living contract&rdquo; form. It is subject to change; without notice anywhere but here&ndash;and there&ndash;in the original spirit of the GPL 2.0. We are &ldquo;one step closer to God&rdquo; &hellip; and do see that in that I mean &hellip; it is a very real fusion of this document and the &ldquo;spirit of my life&rdquo; as well as the Spirit&rsquo;s of Kerouac&rsquo;s America and Vonnegut&rsquo;s Martian Mars and my Venutian Hotel &hellip; and <em>my fusion</em> of Guy-A and GAIA; and the Spirit of the Earth &hellip; and of course the God given and signed liberties in the Constitution of the United States of America. It is by and through my hand that this document and our X Commandments link to the Bill or Rights, and this story about an Exodus from slavery that literally begins here, in the post-apocalyptic American hartland. Written &hellip; this day &hellip; April 14, 2020 (hey, is this HADAD DAY?) &hellip; in Margate FL, USA. For &ldquo;official used-to-v TAX day&rdquo; tomorrow, I&rsquo;m going to add the &ldquo;immultible incarnite pen&rdquo; &hellip; if added to the living &ldquo;doc/app&rdquo;&ndash;<a href="https://rinkeby.aragon.org/#/xcaliber">see is the DAO</a>, the way&ndash;will initi8 the special secret &ldquo;hidden level&rdquo; &hellip; we&rsquo;ve all been looking for.</p>

<p style="text-align: justify;">Nor do just mean this website or the totality of my written works; nor do I only mean &hellip; this particular derivation of the GPL 2.0+ modifications I continually source &hellip; must be &ldquo;from this website.&rdquo; I also mean <em>the thing</em> that is built from &hellip; bits and piece of blocks of sand-toys; from Ethereum and from Rust and from our hands and eyes working together &hellip; from this place, this cornerstone of the message that is &hellip; written from brick and mortar words and events and people that have come before this poit of the &ldquo;sealed W&rdquo; that is this specific page, and this time. It&rsquo;s 3:28; just five minutes&ndash;or is it four, too layne.</p>

<p style="text-align: justify;">This work is not to be redistributed according to the GPL unless all linked media on Youtube and related sites are intact&ndash;and historical references to the actual documented history of the art pieces (as I experience/d them) are also available for linking. Wikipedia references must be available for viewing, as well as the exact version of those pages at the time these pieces were written. All references to the Holy Bible must be &ldquo;linked&rdquo; (as they are or via &hellip; impromptu in-transit re-linking) to the exact verses and versions of the Bible that I reference. These requirements, as well as the caveat and informational re-introduction to God&rsquo;s DAO above &hellip; should be seen as material modifications to the original GPL2.0 that are retroactively applied to all works distributed under license via this site and all previous e-mails and sites. /s/ wso</p>
</blockquote>

<p style="text-align: center;"><a href="https://imgur.com/user/adobrin/posts"><img alt="" src="./i.imgur.com/612s6xq.png" style="height: 393px; width: 500px;" /></a></p>
</div>

