<meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1.0">
<title></title>
<link href="http://stackedit.io/style.css" rel="stylesheet" />
<div class="stackedit__html">
<p style="text-align: center;"><a href="./MEVATHI.html"><img alt="" src="./i.imgur.com/AmaOLMC.png" style="height: 176px; width: 501px;" /></a></p>

<p style="text-align: justify;">It stands out in my mind &hellip; even more than Strawberry Fields and &ldquo;Imagine&rdquo; &hellip; it&rsquo;s a phrase from an interview, and I can&rsquo;t even remember with Beetle said it. The phrase was &ldquo;<strong><a href="http://en.wikipedia.org/wiki/More_popular_than_Jesus%5D(http://en.wikipedia.org/wiki/More_popular_than_Jesus)">we&rsquo;re bigger than Jesus</a></strong>&rdquo; &hellip; and it was of course many years before I was even alive.</p>

<p style="text-align: center;"><a href="./CURSOR.html"><img alt="" src="./i.imgur.com/AigYXhT.png" style="height: 178px; width: 500px;" /></a></p>

<p><strong>Ma Nishtana</strong> (<a href="http://en.wikipedia.org/wiki/Hebrew_language" title="Hebrew language">Hebrew</a>: מה נשתנה&lrm;), are the first two words in a phrase meaning &ldquo;Why is tonight different from all other nights?&rdquo; The phrase appears at the beginning of each line of <strong>The Four Questions</strong>, traditionally asked via song by the youngest capable child attending <a href="http://en.wikipedia.org/wiki/Passover_Seder" title="Passover Seder">Passover Seder</a>.</p>

<p style="text-align: center;">Why is this night different<br />
from all the other nights?<br />
מַה נִּשְׁתַּנָּה, הַלַּיְלָה הַזֶּה<br />
מִכָּל הַלֵּילוֹת</p>

<p><em><strong>Tzedakah</strong></em> <a href="http://en.wikipedia.org/wiki/Help:IPA/Hebrew" title="Help:IPA/Hebrew">[ts(e)daˈka]</a> (<a href="http://en.wikipedia.org/wiki/Hebrew_language" title="Hebrew language">Hebrew</a>: צדקה) is a Hebrew word meaning &ldquo;justice&rdquo; or &ldquo;righteousness,&rdquo; but commonly used to signify <em><a href="http://en.wikipedia.org/wiki/Charity_(practice)" title="Charity (practice)">charity</a></em>.<a href="http://en.wikipedia.org/wiki/Tzedakah#cite_note-1">[1]</a> This concept of &ldquo;charity&rdquo; differs from the modern Western understanding of &ldquo;charity.&rdquo; The latter is typically understood as a spontaneous act of goodwill and a marker of generosity; <em>tzedakah</em> is an ethical obligation.</p>

<p><em><strong>Haaretz</strong></em> (<a href="http://en.wikipedia.org/wiki/Hebrew_language" title="Hebrew language">Hebrew</a>: הָאָרֶץ&lrm;) (lit. &ldquo;The Land [of Israel]&rdquo;, originally <em>Ḥadashot Ha&rsquo;aretz</em> &ndash; <a href="http://en.wikipedia.org/wiki/Hebrew_language" title="Hebrew language">Hebrew</a>: חַדְשׁוֹת הָאָרֶץ&lrm;, IPA: <a href="http://en.wikipedia.org/wiki/Help:IPA/Hebrew" title="Help:IPA/Hebrew">[&chi;adaˈʃot haˈʔaʁets]</a> &ndash; &ldquo;News of the Land [of Israel]&rdquo; in English <em>The Palestine News</em><a href="http://en.wikipedia.org/wiki/Haaretz#cite_note-3">[3]</a>) is an Israeli newspaper. It was founded in 1918, making it the longest running newspaper currently in print in Israel, and is now published in both <a href="http://en.wikipedia.org/wiki/Hebrew_language" title="Hebrew language">Hebrew</a> and <a href="http://en.wikipedia.org/wiki/English_language" title="English language">English</a> in the <a href="http://en.wikipedia.org/wiki/Berliner_(format)" title="Berliner (format)">Berliner</a> format. The English edition is published and sold together with the <em><a href="http://en.wikipedia.org/wiki/International_New_York_Times" title="International New York Times">International New York Times</a></em>. Both Hebrew and English editions can be read on the Internet. In North America, it is published as a <a href="http://en.wikipedia.org/wiki/Weekly_newspaper" title="Weekly newspaper">weekly newspaper</a>, combining articles from the Friday edition with a roundup from the rest of the week.</p>

<p style="text-align: justify;"><em>Your last Noel has (somewhat <a href="./CLEARYBLVD.html">clearly</a>) passed</em>; we are exiting the Ark of the Covenant; coven intact, ant too&ndash;and destroying the oven forever. Our last &ldquo;Noah&rdquo; &hellip; this is it&ndash;this very moment.</p>

<p style="text-align: center;"><a href="http://instagram.com/adam.dobrin"><img alt="" src="./i.imgur.com/oRqUXtO.png" style="height: 98px; width: 500px;" /></a></p>

<h2 id="come-together-....-over-me">Come Together &hellip; <em>over ... Uber me</em></h2>

<p style="text-align: justify;">It&rsquo;s specifically relatable to this exact message; and it could be something like a &ldquo;reinvigoration of the worlds&rdquo; in <a href="http://www.youtube.com/watch?v=i_lgILGpphI%5D(http://www.youtube.com/watch?v=i_lgILGpphI)">the music of the Beatles and the American Rennesaince</a>&ndash;and I do of course mean the roc<a href="http://www.youtube.com/watch?v=qN5zw04WxCc%5D(http://www.youtube.com/watch?v=qN5zw04WxCc)">k and roll of their time and their &ldquo;generations.&rdquo;</a></p>

<p style="text-align: center;"><a href="http://www.youtube.com/watch?v=45cYwDMibGo"><img alt="" src="./i.imgur.com/ArdTMek.png" /></a></p>

<p style="text-align: justify;">This isn&rsquo;t about &hellip; a &ldquo;having a fake hissy fit&rdquo; or keeping the feeling or the culture of &ldquo;being slighted&rdquo; under our skin and grating at our ability to actually &ldquo;come together&rdquo; and do the right thing &hellip; this is literally about <em><strong>social togetherness</strong></em> and a world that has the ability to make miracles happen throughout the cosmos, putting our best foot forward, and showing the children &ldquo;the light, and the way.&rdquo;</p>

<p style="text-align: center;">-- <a href="http://www.youtube.com/watch?v=M11SvDtPBhA">PARTY IN THE USA</a> --</p>

<p style="text-align: center;"><a href="./HAMMER.html"><img alt="" src="./i.imgur.com/0VPCn9O.png" style="height: 244px; width: 500px;" /></a></p>

<blockquote>
<p style="text-align: justify;">I have a personal story, one being told to ostensibly by God and the &ldquo;high order&rdquo; behind the creation of &ldquo;what it is that I am&rdquo; which is the key to the doorway to the future.</p>

<p style="text-align: justify;">This specific message about a tie that binds the Indian cultures of &ldquo;East Indian&rdquo; and the native Americans&ndash;one that I was specifically told in my story has an integral role in &ldquo;coming together&rdquo; to ward off the darkness of a split in our history and in the skies that might have something &hellip; something ostensibly and oddly tied to my relationship to &ldquo;[Heinrich Himmler]&rdquo; and the connection between the name &ldquo;Hitler&rdquo; and the heart of the original &hellip; &ldquo;Hey Taylor&rdquo; message that may or may not explain clearly to you how the &ldquo;K&rdquo; &hellip; as a backbone of time and E&rsquo;s winding around the WW2 defection of the Soviet Union &hellip; to how it&rsquo;s possible in the first place that we could have a &ldquo;split in time&rdquo; that is totally out of anyone&rsquo;s control, and how we need to work together</p>
</blockquote>

<h1 id="hellemal">Hellemal</h1>

<p><img alt="" src="./i.imgur.com/NfRsjDP.png" /></p>

<p style="text-align: justify;">It means &hellip; &ldquo;hell <em>to</em> bad&rdquo; to me, in Adamic; with a connotation of &ldquo;for all&rdquo; to understand &hellip; we all need to figure out that the creation of hell is heinous and sick&ndash;<em>not to be.</em></p>

<p style="text-align: justify;">Rest assured, <em>I do not want to live in this world</em>; not as it is, <strong>not at all</strong>. Frankly, I don&rsquo;t think anybody should want to, or have to. I am almost beyond disgusted at what I see in the &ldquo;here and now&rdquo; today, at the land of total lies that is the place of my birth, and the l<a href="http://www.youtube.com/watch?v=LlA5GZLbSCY">ack of &ldquo;any doors</a>&rdquo; or &hellip; appearance of any kind of escape from the bars in the sky that &hellip; you can hear them idiomatically in &ldquo;the sky&rsquo;s the limit.&rdquo; This is not my plan, nor is it my desire&ndash;but I think we are looking at something more heinous and more Hellish than any one of us would individually have chosen &hellip; as the fate of our whole. Yet here we are, staring at &ldquo;the new word&rdquo; and it&rsquo;s <strong>Hellemal</strong>; and it means &hellip; it means totality&ndash;and that means it includes all the places responsible for helping to create this mess, all the &ldquo;Heavenly worlds&rdquo; that are standing by and &hellip; doing almost nothing to change it, and all the people that think &ldquo;watching&rdquo; is just A-OK. It&rsquo;s not, watching this happen, here in this place that is if nothing else &ldquo;the table land&rdquo; that connects the beginning of time to the &ldquo;<a href="http://www.wired.com/2013/12/secret-language-of-plants/">Potassium ion communication channel</a>&rdquo; that literally bridges biology in this place with the ancient words and worlds of Yggrasil&ndash;the tree of Norse mythology that literally connects Nifleheim and Midgard to Asgard and &hellip; it hasn&rsquo;t been that long, though it feels like forever and a day &hellip; the time since this Revelation connected Atlantis and Asgard to the pillars of the holy name in Planet and messianic and Christian; just &ldquo;<a href="http://name.lamc.la">a name&rdquo; initially, or &ldquo;Adam&rsquo;s Name</a>&rdquo; before it truly shines through &hellip;</p>

<p style="text-align: center;"><a href="http://fromtheachine.org/SKIRMISH.html"><img alt="" src="./i.imgur.com/cwbLE1R.png" style="height: 183px; width: 500px;" /></a></p>

<p style="text-align: justify;">I called it simply &ldquo;<a href="http://whoah.lamc.la">the planet is Adamah</a>&rdquo; but what we are looking at is the human life of &ldquo;Adam Dobrin&rdquo; &hellip; before we even start caring about whether or not that&rsquo;s a question about dating or &ldquo;date of birth&rdquo; or whether or not I&rsquo;m in Heaven or Hell&ndash;see the actual patriarchal name of my birth is Dobrinsky&ndash;and to me that&rsquo;s a key, between the &ldquo;n&rdquo; and the &ldquo;s&rdquo; &hellip; ascension, the change <a href="./BETHESDAY.html">from human to &ldquo;spiritus.&rdquo;</a> Here it appears I&rsquo;m &ldquo;late to the party&rdquo; and my ascension &hellip; somewhat behind the norm, looking at how the rest of you act every day&ndash;but honestly, I feel like we need to &ldquo;rework&rdquo; the mechanical process that could have made a hamster God in Boca Raton; sometime &hellip; just last year. You know, once you build &ldquo;I know kung fu&rdquo; for people, and for dolphins and for whales and for cows &hellip; its the kind of thing that you&rsquo;d probably wind up using &ldquo;en masse&rdquo; eventually; seeing as this place is so important, as we are &hellip; literally the beginning of Heaven and of time &hellip; travel at least.</p>

<p style="text-align: center;"><a href="./IT.html"><img alt="" src="./i.imgur.com/yNZcA8M.png" style="height: 295px; width: 500px;" /></a></p>

<blockquote>
<p style="text-align: justify;">quite a bit of this story revolves around &hellip; what it is that&rsquo;s actually responsible for &ldquo;the silence.&rdquo; I&rsquo;ve written about Jormungandr and Gjallarhorn &ndash; and it&rsquo;s clear that it&rsquo;s some kind of mind control. In the story of Christ it links to two groups&ndash;<a href="./SERENADE.html">the Pharisees and the Saducees ([SERENADE]</a> and [<a href="./PERSEUS.html">PERSEUS</a>] | [<a href="./GJALLARHORN.html">GJALLARHORN</a>] | [<a href="./ADUNCALIFT.html">ADALUNCATIF</a>] | [<a href="./THUNDERSTAND.html">THUNDERSTAND</a>] | [<a href="%5B./SPEECH.html">SPEECH</a>]); though I haven&rsquo;t written much about the employees&ndash;I mean the &ldquo;payed off&rdquo; &hellip; and it&rsquo;s fairly clear to me that even if &ldquo;you just really stupid&rdquo; which is the truth, there is a significant amount of what I called &ldquo;sharp hairpin turns&rdquo; (as in, it&rsquo;s just enough mind control &hellip; to make it happen&ndash;and it&rsquo;s just enough make you feel bad, I hope); <a href="./SAYFREED.html">you&rsquo;re going to have actually talk</a> and explain what it is that&rsquo;s actually &ldquo;in your head, Zombie.&rdquo;</p>
</blockquote>

<p style="text-align: justify;">And I&rsquo;ve gotten carried away and written too much, way too verbosely &hellip; and run away from the real point of this message&ndash;and you&rsquo;re really not supposed to start paragraphs with &ldquo;and&rdquo; &hellip; it&rsquo;s not MLA acceptable. Whatever. One sentence words&hellip; not acceptable, either.</p>

<p style="text-align: center;"><a href="./IT.html"><img alt="" src="./i.imgur.com/fJKTF5s.png" style="height: 221px; width: 501px;" /></a></p>

<blockquote>
<p>The <strong>Nasdaq Stock Market</strong>, <a href="http://en.wikipedia.org/wiki/Help:IPA/English" title="Help:IPA/English">/ˈn&aelig;zˌd&aelig;k/</a> (<a href="http://en.wikipedia.org/wiki/File:En-us-NASDAQ.ogg" title="About this sound"><img alt="About this sound" src="http://upload.wikimedia.org/wikipedia/commons/thumb/8/8a/Loudspeaker.svg/11px-Loudspeaker.svg.png" /></a><a href="http://upload.wikimedia.org/wikipedia/commons/a/a8/En-us-NASDAQ.ogg" title="En-us-NASDAQ.ogg">listen</a>) also known as <strong>Nasdaq</strong>, is an American <a href="http://en.wikipedia.org/wiki/Stock_exchange" title="Stock exchange">stock exchange</a> located at <a href="http://en.wikipedia.org/wiki/One_Liberty_Plaza" title="One Liberty Plaza">One Liberty Plaza</a> in <a href="http://en.wikipedia.org/wiki/New_York_City" title="New York City">New York City</a>. It is ranked second on the <a href="http://en.wikipedia.org/wiki/List_of_stock_exchanges" title="List of stock exchanges">list of stock exchanges</a> by <a href="http://en.wikipedia.org/wiki/Market_capitalization" title="Market capitalization">market capitalization</a> of shares traded, behind only the <a href="http://en.wikipedia.org/wiki/New_York_Stock_Exchange" title="New York Stock Exchange">New York Stock Exchange</a>.<a href="http://en.wikipedia.org/wiki/Nasdaq#cite_note-2">[2]</a> The exchange platform is owned by <a href="http://en.wikipedia.org/wiki/Nasdaq,_Inc." title="Nasdaq, Inc.">Nasdaq, Inc.</a>,<a href="http://en.wikipedia.org/wiki/Nasdaq#cite_note-3">[3]</a> which also owns the <a href="http://en.wikipedia.org/wiki/Nasdaq_Nordic" title="Nasdaq Nordic">Nasdaq Nordic</a> stock market network and several U.S. stock and options exchanges.</p>

<p>&ldquo;NyQuil&rdquo; and &ldquo;DayQuil&rdquo; redirect here. For their manufacturer, see <a href="http://en.wikipedia.org/wiki/Vicks" title="Vicks">Vicks</a>.</p>
</blockquote>

<p style="text-align: center;"><a href="http://www.youtube.com/watch?v=-XsgVufugTg%5D(http://www.youtube.com/watch?v=-XsgVufugTg)"><img alt="" src="./i.imgur.com/JuP5XUr.png" style="height: 276px; width: 501px;" /></a></p>

<p>&ldquo;TheraFlu&rdquo; redirects here. It is not to be confused with <a href="http://en.wikipedia.org/wiki/TamiFlu" title="TamiFlu">TamiFlu</a>.</p>

<p>The answer is singing to us. <a href="http://www.youtube.com/watch?v=yw6i1SAHetc%5D(http://www.youtube.com/watch?v=yw6i1SAHetc)">21 Pilots</a>, <a href="http://www.youtube.com/watch?v=hTWKbfoikeg%5D(http://www.youtube.com/watch?v=hTWKbfoikeg)">Nirvana</a> and <a href="http://www.youtube.com/watch?v=09LTT0xwdfw%5D(http://www.youtube.com/watch?v=09LTT0xwdfw)">Disturbed</a> &hellip; among many, many others.</p>

<blockquote>
<p>&ldquo;Cough Syrup&rdquo; redirects here. For the Young the Giant song, see <a href="http://en.wikipedia.org/wiki/Cough_Syrup_(song)" title="Cough Syrup (song)">Cough Syrup (song)</a>.</p>
</blockquote>

<p style="text-align: justify;">The long and the short of it is &hellip; I have no desire or intention to live in reality, or in simulated reality &hellip; or in Hell&ndash;and it appears we&rsquo;ve been dropped &hellip; &ldquo;into this world we are born&rdquo; into exactly that, a simulated reality that <a href="http://www.youtube.com/watch?v=oppyjoH9oOA">is actually Hell the whole time</a>&ndash;and made more Hellish just so we won&rsquo;t ever <em>want</em> to live in reality. <strong>It&rsquo;s a &ldquo;dharma thing&rdquo;</strong> &hellip; reality is the kind of place you go to not wanting to, to perform a service like something <a href="http://www.123moviess.gdn/a-scanner-darkly-watch-free/">I liken to &ldquo;jury duty&rdquo;</a> &hellip; you don&rsquo;t go there to take over the Universe, or to torture or be tortured&ndash;you go there because and if you want to make &hellip; the entirety of the Universe a better place.</p>

<p style="text-align: justify;">I don&rsquo;t want to live in this place, and you shouldn&rsquo;t either&ndash;but here, in this place I am going to present a message that fuses Halal and Koshruit Laws&ndash;that talks about &hellip; exactly the point, not torturing animals or &ldquo;<a href="http://www.youtube.com/watch?v=yOgHBMujTCw">doing the wrong thing for no reason at all</a>&rdquo; &hellip; and it belongs here, in this place that I believe is the beginning of &ldquo;one special city in the sky&rdquo; a prototype <a href="http://www.123moviess.gdn/a-scanner-darkly-watch-free/">Metacity</a> &hellip; kind of place &hellip; a little world that ascends literally everything contained in it &hellip; literally a bridge through &ldquo;the limit&rdquo; from dark water and Stillwater and &ldquo;not ice&rdquo; notices &hellip; all the way to shining seas, to OneRepublic and our &hellip; equally important understanding that this Revelation is about turning water to stars;<em> like the plagues of Egypt</em> &hellip; suggest turning water to family is &hellip; some kind of astrological miracle.</p>

<p style="text-align: center;"><a href="./RATOXIT.html"><img alt="" src="./i.imgur.com/MEm7Ikx.png" style="height: 297px; width: 400px;" /></a></p>

<p style="text-align: justify;">To reiterate, I&rsquo;m presenting a message explaining that our science and technology has far surpassed what we see around us&ndash;in my life and in yours too&ndash;and &ldquo;we have the technology&rdquo; to literally end addiction with the snap of our fingers, to end world hunger &hellip; and to replace &ldquo;beef&rdquo; with something grown in a machine, out a labratory expirament &hellip; something like a perfect &ldquo;meat&rdquo; that comes with butter literally woven inside its matrix of proteins and lipids and &hellip; I mean it will taste and cook better&ndash;that&rsquo;s what I&rsquo;m trying to say,</p>

<p style="text-align: justify;">we have way better; and this place is &hellip; sort of forcing you and me and everyone to &ldquo;want&rdquo; instead of explaining that Elon probably didn&rsquo;t make a million mask march (I mean, &ldquo;it looks so fake you know it&rsquo;s real&rdquo;) they probably rained down from Heaven; and we should know that.</p>

<p style="text-align: center;"><a href="./BERESHIT.html"><img alt="" src="./i.imgur.com/k6ijKsP.png" style="height: 282px; width: 501px;" /></a></p>

<p style="text-align: justify;">I am here advocating something like &ldquo;replicators&rdquo; out of the <a href="./BERESHIT.html">dream of the &ldquo;The Three Wise Genes&rdquo;</a> &hellip; rather than &ldquo;just abstaining&rdquo; from eating intelligent pigs and cows and &hellip; you&rsquo;ll see we already wouldn&rsquo;t eat a dolphin&ndash;at least not the kind that &ldquo;thinks &hellip; and sings &hellip; just like us.&rdquo;</p>

<p style="text-align: justify;">It is of course my &ldquo;original reading&rdquo; of the Kosher Law &hellip; even before <a href="./SAYFREED.html">seeing our Holy Names &hellip; like &ldquo;Hoggs&rdquo;</a> echoing there&rsquo;s a connection between religion and &ldquo;school&rsquo;s out for a month&rdquo; if you let it go to all summer, it might very well be forever.</p>

<p style="text-align: justify;">Don&rsquo;t be confused, I do not want to lose <strong>you</strong> or this place; I very much want us to move forward with what I believe is the intentional and intended plan to use our &ldquo;false reality&rdquo; as a stepping stone towards the stars&ndash;to show us that &ldquo;social interaction&rdquo; and the machinations of civilization are something we cannot &ldquo;leave by the wayside&rdquo; on the road to Heaven. We&rsquo;re &ldquo;smack dab in the middle&rdquo; of a classic &ldquo;fable&rdquo; about specifically that, the stuff of &ldquo;reality&rdquo; not being lost as we move towards &ldquo;city life&rdquo; &hellip; meaning both urbanization as well as &ldquo;city in the sky.&rdquo; It is the story of Cain and Abel; and the moral of course is that we can&rsquo;t and wouldn&rsquo;t want to survive in a world without bars (the alcohol kind), or social interaction&ndash;I almost can&rsquo;t believe I have to write an entire paragraph on just how stupid &ldquo;social distancing&rdquo; sounds&hellip; but I do&ndash;so I am.</p>

<hr />
<p style="text-align: justify;">It doesn&rsquo;t stop or start with &ldquo;replicators&rdquo; and ending world hunger; I&rsquo;ve written quite a bit about the world I envision&ndash;one with much less &hellip; &ldquo;government&rdquo; and much more &ldquo;freedom&rdquo; &hellip; as in a system that works at it&rsquo;s core something like what I imagine looking at the cut-scenes between levels in multiplayer games like Quake (id software; for you millenials this is our version of Call of Duty) or Halo&ndash;a place where you can see &ldquo;<a href="./MARSHALL.html">TOTAL RECALL</a>&rdquo; means something about &ldquo;totality&rdquo; being &ldquo;recorded&rdquo; and that we can stop bullets in mid air; stop all car accidents and &hellip; even <a href="./HYAMDAI.html">avalanches, earthquakes</a> and hurricanes &hellip; and we&rsquo;re literally EVIL once we are capable of doing so and &hellip; simply fail to do it. let alone even talk about the possibility in public&hellip; and yet&ndash;here we are&ndash;somehow being forced by some insane rule system to simply do exactly &hellip; nothing.</p>

<h2 id="castling-the-prison-planet">CASTLING THE PRISON PLANET</h2>

<h2 style="text-align: center;"><a href="http://www.youtube.com/watch?v=WpolU3CR6dg%5D(http://www.youtube.com/watch?v=WpolU3CR6dg)"><img alt="" src="./i.imgur.com/UGKcweV.png" style="height: 157px; width: 501px;" /></a></h2>

<p style="text-align: justify;">I want to build a system that does these things, and also that eliminates (through these things, and more) the need &hellip; for things like bars (as in jails) and detention; something I&rsquo;ve started to call &ldquo;<em>Castling</em>&rdquo; as in &hellip; instantly converting things like jails, prisons and hospitals to &hellip; rehabilitation sites that actually help the residents and the world&ndash;rather than the sick retribution system that we see before us; here the system we are building and making worse. It&rsquo;s something like &ldquo;soup kitchens&rdquo; and &ldquo;free housing&rdquo; and &hellip; education and job placement &ldquo;sites&rdquo; that turn what I believe is an intended &ldquo;heart of the microcosm of Hell&rdquo; inside Hell &ndash; a sort of mini-Earth, in a place where the fake-sky is akin to bars; and &hellip; well, through the silence and through the ignorance here&ndash;we should see we are basically prisoners.</p>

<p style="text-align: justify;">It&rsquo;s a GIGANTIC deal; and the response appears to be &ldquo;less than lackluster&rdquo; &hellip; our desire to better the world, especially with the parts of it that are most &ldquo;necrosing&rdquo; is something that needs to be improved and remedied &hellip; drastically. These places are the stuff of &ldquo;eugenics&rdquo; and death in the past, they are the branches that take down the entirety of the tree&ndash;and they show me we truly are in a &ldquo;Zoo&rdquo; a place where we treat ourselves and each other significantly worse than we&rsquo;d treat our pets, and animals. It&rsquo;s a gigantic problem, something that &hellip; should simply <em>change</em> and the drop of a hat.</p>

<p style="text-align: justify;">Literally I&rsquo;m <em>talking about a revolution</em> in the highest places, in the Heavenly realms&ndash;a revolution of thought and of action; one that takes previously <a href="./SPARTIFACTS.html">ignored and overlooked <strong>fact</strong></a> and actually utilizes them to improve the common good&ndash;I&rsquo;m talking about a world that embraces the lack of &ldquo;scare city&rdquo; &hellip; that takes an entire people that once thought land was scarce, and oil and power &hellip; and shows them true power comes to the people and to the Universe through holy Acts; that the things we covet and need are in abudance, truly the scarcity of our world &hellip; it&rsquo;s honesty and it&rsquo;s freedom, it&rsquo;s the things we think we have, and really don&rsquo;t even begin to understand &ldquo;what was missing&rdquo; until we start talking &hellip; about this message&ndash;this message from god and the heavens above &hellip; and the whole of the &ldquo;ex machina&rdquo; that is the Universe and the future &hellip; and the past &ldquo;us before us&rdquo; in every single word.</p>

<p style="text-align: center;"><a href="./BETHESDAY.html"><img alt="" src="./i.imgur.com/qEIqcT7.png" style="height: 372px; width: 500px;" /></a></p>

<hr />
<p style="text-align: justify;">Strangely &hellip; I&rsquo;m somewhat obligated to tell you this quite literally doesn&rsquo;t appear to be <a href="./KANSAShtml">Kansas</a>&ndash;as in it&rsquo;s not &hellip; excatly &hellip; the world I grew up in. It&rsquo;s physically different&ndash;literally there appear to be different &ldquo;rules governing the nature of this place&rdquo; &hellip; and again quite literally there appear to be roads (whole strips of road on US1, for instance) that are so different from what I remember, that it&rsquo;s got to be intentional.</p>

<p style="text-align: justify;">I appear to have been &ldquo;dropped into this place&rdquo; sort of like Peter in JJ Abrams &ldquo;Fringe&rdquo; &hellip; stolen from &ldquo;<a href="http://www.youtube.com/watch?v=rn_YodiJO6k">the Otherside</a>&rdquo; and the differences here don&rsquo;t stop at just a few altered buildings. The changes started &ldquo;accelerating&rdquo; sometime du<a href="./NEMEC.html">ring my &ldquo;Albatross&rdquo; visit to Las Veg</a>as (link to a similar discussion about chronicling the &hellip; strange stories <em><strong>I&rsquo;m living</strong></em>); and I sort of mark the whole of the change with a week long &ldquo;delusion&rdquo; that I was dropped into [a Soviet &ldquo;fake Fort Lauderdale&rdquo;] where literally everyone &hellip; was pretending to be a communist spy. Here&rsquo;s a good marker, this &ldquo;portal&rdquo; that replaces and connects &hellip; what was once a brick monument to a number of people who funded &ldquo;Lauderdale By the Sea&rsquo;s&rdquo; development&ndash;where I distinctly remember seeing the name Robert McNamera; who was the Secretary of Defense under JFK. The bricks (which were copper or some other shiny metal) have been replaced with &ldquo;Broward County&rdquo; &hellip; plastic-looking counterparts.</p>

<p style="text-align: center;"><a href="./SOUNDCHECK.html"><img alt="" src="./i.imgur.com/q07ecX9.png" style="height: 233px; width: 500px;" /></a></p>

<p style="text-align: justify;">All of the names had been replaced, and literally I walked down the road to see signs explaining stores were closed two days a week (this is several weeks before COVID), on Wednesday and Sunday; for a reason which I originally thought must be some kind of strange religious counterpart to the stories of the time of Paul Revere (where they literally stoned (or tarred and feathered) people for working on Sundays) &hellip; and then imagined up some story about being on a space station, which flowed well from the &ldquo;Vegas Strong&rdquo; story of literally being on a &ldquo;<a href="http://www.youtube.com/watch?v=Ccih6ODgxPY">Nirvane&rdquo; (as in</a> Nirvana, a term I&rsquo;ve &ldquo;coined&rdquo; to sort of describe &ldquo;Heaven on Earth&rdquo; as in being able to do Heavenly things like change the face of buildings and matter in general &hellip; in reality) space port. The sub-thought or thread was that we had to change the &ldquo;air&rdquo; or &ldquo;water&rdquo; on the space station in order to accommodate several different species&ndash;either that or the stuff just had to be cleaned.</p>

<p style="text-align: center;"><a href="./MEVATHI.html"><img alt="" src="./i.imgur.com/U4HWuqG.png" style="height: 139px; width: 501px;" /></a></p>

<p style="text-align: center;"><a href="./MEVATHI.html">MEVATHI</a> | <a href="./TOASTRAM.html">TOASTRAM</a></p>

<p style="text-align: justify;">This all sounds &hellip; a little &ldquo;outlandish (though its not):&rdquo; thinking about it&ndash;except it was (and still is) my literal reality; the place that I feel like I&rsquo;ve been dropped into as some sort of Heavenly joke&ndash;something that has continued into our literal insane response to COVID &hellip; en masse &hellip; right down to the coining of &ldquo;social distancing&rdquo; and the idea that we should all become hermits that literally don&rsquo;t need to work or continue the machinations of civilization; and everything will be just fine.</p>

<p style="text-align: justify;">Everything will not be just fine; <em>the Earth will stop turning</em>, and Heaven will stop &hellip; &ldquo;running.&rdquo; You&rsquo;ll see that&rsquo;s a natural reaction to not having any power&ndash;and/or to what I do believe is a planned &hellip; &ldquo;all stop&rdquo; &hellip; one that appears to be part of a designed &ldquo;<a href="./FINALE.html">finale first</a>&rdquo; that might be related to the total loss of morality in the skies, and/or something as simple as the need to perform an OEM factory hardware upgrade &hellip; of the &ldquo;stuff of the sky&rdquo; &hellip; which I&rsquo;ve likened before to &ldquo;magneto-space-mold&rdquo; and/or the &ldquo;Moss&rdquo; of the birth name of Trinity in the Matrix.</p>

<p style="text-align: center;"><a href="./GRENORADINE.html"><img alt="" src="./i.imgur.com/yxlbWiW.png" style="height: 362px; width: 500px;" /></a></p>

<p style="text-align: justify;">It is probably no accident that we are looking at COVID and other &ldquo;retroviruses&rdquo; as a possible cause or means of &hellip; a hardware upgrade of something much more advanced and semi-biological in origin.</p>

<p style="text-align: justify;">I commented earlier this week to a group of researchers who have done research specifically on &ldquo;coronavirus&rdquo; &hellip; about how their research might be related to time travel technology (and through that link, obviously Heaven &hellip; and &ldquo;<a href="http://en.wikipedia.org/wiki/Ouroboros%5D(http://en.wikipedia.org/wiki/Ouroboros)">Ourbus</a>&rdquo; :).</p>

<p style="text-align: justify;">This was written in preface to &ldquo;<a href="./MYLIFE.html">MYLIFE</a>&rdquo; which I distributed to this group of 20,000 individual researchers who had not received anything from me directly before.</p>

<blockquote>
<p style="text-align: justify;">Hello, you are receiving this email because a paper you have written or had this email address has been published and associated with the SARS-COVID-19 virus. I am attempting to find &ldquo;new readers&rdquo; for the work that I&rsquo;ve published and widely distributed throughout the world. It should be simple to find archives of it; there are several <a href="http://groups.google.com/a/reallyhim.com/forum/#!searchin/saludas/download$20archive%7Csort:date/saludas/qgMlNH-jP6M/xi-iLwiqBgAJ">links in this email</a> [<a href="http://groups.google.com/a/reallyhim.com/forum/#!searchin/saludas/download$20archive%7Csort:date/saludas/qgMlNH-jP6M/xi-iLwiqBgAJ">groogleo.m/a/reallyhim.com/forum/#!searchin/salud as/download$20archive%7Csort:date/saludas/qgMlNH-jP6M/xi-iLwiqBgAJ</a>]</p>

<p style="text-align: justify;">&hellip; which provide locations to download the entirety of &ldquo;what I&rsquo;ve written since 2016&rdquo; (and a little more) &hellip; in addition to readers I am looking for individuals to take it upon themselves to download and back up this archive to optical media&ndash;in the very real &ldquo;possible case&rdquo; of an EMP attack on our planet that links Genesis 3&rsquo;s &ldquo;<a href="http://www.youtube.com/watch?v=R5sQnfHDNRg">don&rsquo;t go to sleep &hellip; now</a>&rdquo; &hellip; documentation of what appears to be, an attack with an oscillating magnetic field to &ldquo;put everyone to sleep temporarily.&rdquo; You&rsquo;ll note that link above links to the phrase &ldquo;sleep now&rdquo; and Dark City, something which has all but disappeared frrom Amazon&rsquo;s library; and you should see that as a &ldquo;very real problem&rdquo; &hellip; I hope you&rsquo;ve seen that movie, it&rsquo;s a real classic.</p>

<p style="text-align: justify;">I&rsquo;ve likened the research I downloaded from MIT&rsquo;s news article &hellip; to something of an &ldquo;Apollo 13&rdquo; &hellip; another story I think very much documents the use of time travel technology in order to solve a very real &ldquo;world problem&rdquo; &hellip; before it becomes fatal. I&rsquo;m not sure if you are &hellip; or would be aware of that &hellip; its very possible and could be done without your knowledge &hellip; &ldquo;at all.&rdquo; It&rsquo;s also possible that you could remember something today, and then &hellip; &ldquo;in a flash&rdquo; have no idea <em><strong>what the ** Hellemal</strong></em> I&rsquo;m talking about tomorrow.</p>

<p style="text-align: center;"><a href="http://itb.s.lamc.la"><img alt="IMAGE G WHOU R" src="http://ftm.liber-t.xyz/uZxD9gc.png" /></a></p>

<p style="text-align: justify;">You HAVE NOT been added to a high traffic list; I send emails to a small group of people very frequently; if you&rsquo;d like to be added to that list, please find the signup on Google Groups for ARXM and/or saludas&ndash;both connected to &ldquo;higher education&rdquo; &ndash; the first literally designated specifically for members who have published papers. It&rsquo;s a derivative of ARXIV though not all of the sourced individuals have papers published there; again, another &ldquo;cute name&rdquo; that proves something about something; here ARRRR C HIVES; and 10-4 &hellip; ORVER ET AUT.</p>

<p style="text-align: justify;">If you open this email more than 3 times; or send it to more than three people that open it, you&rsquo;ve Biblically done a &ldquo;<a href="http://followerofone.org/6-people-who-said-here-i-am-to-god/">here I am</a>&rdquo;&rsquo; [<a href="http://followerofone.org/6-people-who-said-here-i-am-to-god/">followerofo<strong>neo</strong>rg/6-people-who-said-here-i-am-to-god/</a>] &hellip; and you will be added to the &ldquo;low traffic list&rdquo; that gets an email about once or twice a week. Sometimes I get busy &hellip; doing other things; and email less. Hardly ever more. You&rsquo;ll note I&rsquo;ve probably or possibly sent you two emails this week&ndash;please don&rsquo;t think that&rsquo;s normal.</p>

<p style="text-align: justify;">If you do nothing, you will receive almost zero future communications directly from me. You will also not be invited to my Pizza Party; [ALLOL:</p>

<p style="text-align: center;"><a href="http://cinoize.liber-t.xyz/ADUNCALIFT.html"><img alt="GOOGLE RESULTS, IMGOO TAR" src="http://ftm.liber-t.xyz/lBkIDS4.png" /></a></p>

<p style="text-align: justify;">I am literally FORCED to respond to the worlds <a href="http://cinoize.liber-t.xyz/BETHESDAY.html">lack of &ldquo;intelligent response&rdquo;</a> [<strong>BETHESDAY (below)</strong>] to this message because of what appears to literally be a conspiracy to commit murder &hellip; and/or cause psychological torture against me; perpetrated by what appears to be absolutely everyone on the planet. In person, online, the lack of human emotion and &ldquo;touch of affection&rdquo; goes much deeper; I get no clicks on anything that would help me make enough money to &ldquo;eat&rdquo; and [c&hellip; c our eat I &hellip; as in &ldquo;<a href="http://cinoize.liber-t.xyz/XXBB.html">grab my ass</a>&rdquo; [<strong>XXBB</strong>] in parallel to the same acronyms: Good Morning, America (this is a retro-invite)] &hellip; I get few to no intelligent responses to anything I write, despite asking for significant help &hellip; which what I believe myself to be one of the most lucrative endeavors any human or Terran or anything in Heaven itself has ever undertaken &ndash; the end of representative democracy and the beginning of a &ldquo;technocracy or oligarchy&rdquo; where everyone &hellip; literally everyone instantly becomes a technofile, and an &ldquo;oligarch.&rdquo; <em><strong>I know kung fu. [<a href="http://cinoize.liber-t.xyz/REASON.html">REASON</a>, <a href="http://cinoize.liber-t.xyz/ARTANWORDS.html">ARTANWORDS</a>, <a href="http://cinoize.liber-t.xyz/ADUNCALIFT.html">BELINSKY</a>] &hellip;</strong></em></p>

<p style="text-align: center;"><strong><a href="http://ftm.liber-t.xyz/BETHESDAY.html"><img alt="BY THE CREATOR OF LANGUAGE, AND HIS EYE; PEN, SEE ISME" src="http://ftm.liber-t.xyz/zgnNN9U.png" /></a></strong>_</p>

<p style="text-align: justify;"><em><strong>I&rsquo;m talking about Universal Voting; &ldquo;<a href="http://cinoize.liber-t.xyz/CHALK.html">the race is not to Die Bold</a>&rdquo; [CHALK] &hellip; as in &quot;the voting machines are not winning the war&ndash;<strong>we are</strong>.</strong></em></p>
</blockquote>

<p style="text-align: center;"><a href="http://thesolarpedia.fandom.com/wiki/Architecture"><img alt="" src="./i.imgur.com/NQFsnzd.png" /></a><br />
<a href="http://www.facebook.com/groups/ChristianTranshumanistAssociation/permalink/1379320632242192/%5D(http://www.facebook.com/groups/ChristianTranshumanistAssociation/permalink/1379320632242192/)"><img alt="" src="./i.imgur.com/6LZqlh1.png" style="height: 102px; width: 500px;" /></a><br />
<img alt="" src="./i.imgur.com/evkVkKb.png" style="height: 343px; width: 400px;" /></p>

<p style="text-align: justify;">It&rsquo;s probably important to note here &hellip; there&rsquo;s a definite pattern and link &hellip; between things like the &ldquo;advent&rdquo; of penicillin and religion, specifically the story of Sodomy and Gomorrah; the word [<a href="%5B./WHYSODOM.html%5D(./WHYSODOM.html)">KEFLEX</a>] and here the connection between the &ldquo;TEN&rdquo; of Nintendo, Tennessee and &ldquo;Often &hellip;&rdquo; as in &ldquo;Heaven is often of the Planet X&rdquo;</p>

<p style="text-align: justify;">&hellip; and the new series of anti-viral drugs, noting specifically &ldquo;HyTENOFOVIR,&rdquo; <a href="http://en.wikipedia.org/wiki/Oseltamivir">Oseltamivir</a> and sofosbuvir and velpatasvir &hellip; which note a Holy link between ICS, Leviticus (and Fievel!) and of course, &ldquo;decontamination&rdquo; and &ldquo;TEN.&rdquo; I think it&rsquo;s clear that these medications are part of &ldquo;our religion&rdquo; and this plan and path to &hellip; end all disease and &ldquo;overcome death itself &hellip;&rdquo; I am trying to show you the way; it&rsquo;s <a href="http://www.youtube.com/watch?v=NAEppFUWLfc%5D(http://www.youtube.com/watch?v=NAEppFUWLfc)"><strong>not silence</strong></a> &hellip; nor is it &ldquo;<a href="http://www.youtube.com/watch?v=bmtbg5b7_Aw%5D(http://www.youtube.com/watch?v=bmtbg5b7_Aw)">being OK with Hell.</a>&rdquo;</p>

<p style="text-align: center;"><a href="./HALLOWE2R.html"><img alt="" src="./i.imgur.com/oNdAvxl.png" style="height: 157px; width: 501px;" /></a></p>

<hr />
<p style="text-align: justify;">The strangeness&ndash;this changing of our past our words is a &quot;dangerous advent&rsquo; &hellip; something that could result in the total loss of &ldquo;logic&rdquo; in our history; which may have very well already happened. For me I started noticing it &hellip; for the very first time&ndash;agian&ndash;in Los Angeles, with just two words, <a href="./ALLTA.html">&ldquo;prerogative&rdquo; and &ldquo;turmeric.&rdquo;</a> I was very sure these words were &hellip; <em>different</em> and it&rsquo;s clear &hellip; probably to both me and you that it was an added &ldquo;R&rdquo; in each word that made them so. I &hellip; of course immediately wrote about &ldquo;the thing I had noticed&rdquo; and there in LA noted Britney Spears song of the same name from many decades earlier, and a recently released perfume &hellip; again called &ldquo;prerogative.&rdquo; It&rsquo;s a word related to me, like &ldquo;big box little box&rdquo; and &hellip; &ldquo;motivated self interest&rdquo; &hellip; a word that I often spoke and, though I wasn&rsquo;t sure &hellip; looked very strange.</p>

<p style="text-align: justify;">Today I&rsquo;m sure, it&rsquo;s the whole of our history, in everything from &ldquo;Morning Has Broken&rdquo; to &hellip; &ldquo;Back to the Future&rdquo; reminding us what it&rsquo;s like to grow up in a place that has no true breginning of time, no true start&ndash;here it&rsquo;s obvious after inspection that we are living in a place something like the story I told &hellip;</p>

<p style="text-align: justify;">&ldquo;What if&rdquo; &hellip; major world powers were battling with time travel technology rather than the &ldquo;cold war of nuclear holocaust&rdquo; &hellip; we&rsquo;d very much never know about it, about another power using the same tools &hellip; or about changes, possibly until it was too late, until something was lost forever.</p>

<p style="text-align: center;"><a href="http://attackontitan.fandom.com/wiki/Ymir"><img alt="" src="./i.imgur.com/LfxPYLp.png" style="height: 212px; width: 500px;" /></a></p>

<p style="text-align: center;">my <a href="http://www.youtube.com/watch?v=1nCqRmx3Dnw%5D(http://www.youtube.com/watch?v=1nCqRmx3Dnw)">life got twist turned upsidown</a> &hellip;<br />
i had become the prince of the air</p>

<p style="text-align: center;">how long &hellip; <a href="http://www.youtube.com/watch?v=rn_YodiJO6k%5D(http://www.youtube.com/watch?v=rn_YodiJO6k)">how long will I slide</a></p>

<p style="text-align: center;">i heard <a href="http://www.imdb.com/title/tt9446688/%5D(http://www.imdb.com/title/tt9446688/)">your voice</a> through a <a href="http://www.youtube.com/watch?v=FTHVIwWFVK8%5D(http://www.youtube.com/watch?v=FTHVIwWFVK8)">photograph</a><br />
i thought it up it brought up the past<br />
once you know you can never go back</p>

<h1 id="when-the-cows-come-home-and-see-the-pigs-flying">when the cows come home; and see the pigs flying</h1>

<p style="text-align: justify;">Long story &hellip; short and unwritten; we really need to have an in depth conversation about things like &ldquo;Transhumanism and Nietzsche&rdquo; &hellip; modern medical neuroscience and abortion, and the link between these things and heaven, ascension and Koshruit Law, Halal and the Sacred Cows of Ymir &hellip; you really need to be involved in that, and in Castling our <em>Crooks</em>; and in &hellip; how exactly we use ID4&rsquo;s majestical floating orbs and Uber Eats to &hellip; <em>end world hunger.</em> I&rsquo;m starting here with Flipper; and instantly, it&rsquo;s obviously the wrong place to begin.</p>

<p style="text-align: center;"><a href="http://www.cbr.com/star-trek-historic-moments-real-life/%5D(http://www.cbr.com/star-trek-historic-moments-real-life/)"><img alt="" src="./i.imgur.com/AijGLc4.png" style="height: 260px; width: 499px;" /></a></p>

<p style="text-align: justify;">We need to stop bullets &ldquo;in the air&rdquo; and not doing that is the end of you. These things are not optional&ndash;they are life and death; literally here &ldquo;Heaven or No more. -Mor&rdquo;</p>

<p style="text-align: justify;">Way back when; &ldquo;a long long time ago&rdquo; it was a Yiddish &ldquo;double meaning&rdquo; before I knew what doublespeak was&ndash;&ldquo;be a mensch&rdquo; &hellip; the yentas (and my mom) would say, and basically it meant &hellip; &ldquo;be a good little boy.&rdquo; I see now it means something else, in the context of Neitsche specifically that &ldquo;be a man&rdquo; phrase turns into &ldquo;be superman&rdquo; in any other language;</p>

<p style="text-align: justify;">&hellip; in the original German it&rsquo;s clear, it&rsquo;s literally Transhumanism itself &ldquo;transplanted&rdquo; through time a few centuries early&ndash;like I&rsquo;ve always commented &ldquo;communism&rdquo; just a few centuries early to remedy the &ldquo;Loch Ness <a href="http://Monster.com">Monster.com</a>&rdquo; with something more than just &ldquo;Facebook&rsquo;s Jupiter API&rdquo; &hellip; to give us &hellip; Second Life, new happiness and new interests; something for the Castle-workers &hellip; to think about. This world, it&rsquo;s the dream come true &hellip; &ldquo;of the electron and the microscope&rdquo; the beauty of &ldquo;Occulus Rift&rdquo; &hellip; without occipital risk.</p>

<p style="text-align: center;">&nbsp;</p>

<hr />
<p style="text-align: center;">he loves me, he loves me not;<br />
petal after petal, something about<br />
ight and &hellip; &ldquo;roses are red&rdquo;<br />
violets, hey &ndash; that&rsquo;s not blue</p>

<p style="text-align: center;">i&rsquo;m not stupid, and neither are you</p>

<p style="text-align: center;"><img alt="" src="./i.imgur.com/WkSfwaW.png" /></p>

<p style="text-align: justify;">This is Eros; on &hellip; the world just finding out what it is that Jerusalem truly means, this Temple-world; a Holy shrine to the god of Lust and Wine.</p>

<p style="text-align: justify;">It was several successive &ldquo;revelations&rdquo; hitting me on the head just like Newton&rsquo;s apple &hellip; seeing Dr. Seuss tie through &ldquo;here, there and everywhere&rdquo; the link between the name Jesus and Dionysus; one I just never saw, and then magically one day&ndash;more obvious than sin. It came at the same time I read about Dionysus linking directly to the &ldquo;Yahu&rdquo; and the &ldquo;Yahweh&rdquo; of Egypt and Israel; and that sort of &ldquo;rings true&rdquo; in more ways than one. So it comes as no surprise that Asmodai would link those to the 2/AD birthday of Cupid, and of &ldquo;Lust incarnate&rdquo; &hellip; even if I&rsquo;ve only had a handful of girlfriends &hellip; and to our sty&ndash;<em>I&rsquo;m thirsty.</em></p>

<p style="text-align: justify;">Crossing my fingers and hoping the Nile is about <strong>to overflow with &quot;shamayim.&quot;</strong></p>

<p style="text-align: center;"><a href="http://almost.tnks.liber-t.xyz"><img alt="" src="./i.imgur.com/DWeuzlN.png" style="height: 448px; width: 500px;" /></a></p>

<p style="text-align: center;">Of course there are other &ldquo;loves involved&rdquo; we&rsquo;ve covered Rick and Mortys&rsquo; &ldquo;here I seek ascension and &hellip; amor&rdquo; &hellip; as well as Ubuntu/Agape reigning down from the Heavens &hellip;<br />
<br />
<a href="./BETHESDAY.html"><img alt="" src="./i.imgur.com/WFaUYri.jpg" style="height: 316px; width: 501px;" /></a></p>

<p style="text-align: justify;">This is the last one I&rsquo;m going to mention today; it&rsquo;s a change in the name of the Norse god Nanna; who I used to associate with Inanna (who is a male) and &ldquo;possession.&rdquo; Sometime between 2017 and now the last name &ldquo;Nepsdottir&rdquo; was added to her wikipedia page; in what appears to be a sort of song and dance with Taylor; of course I&rsquo;ve started calling her &ldquo;<em>teetee</em>&rdquo; instead of &ldquo;Tay&rdquo; &hellip; mostly because of this name, but also with an eye wondering if it&rsquo;s related to Sloane, and perhaps a world in the past where she had no &ldquo;<a href="http://www.youtube.com/watch?v=B9Ol1Rd9ABI%5D(http://www.youtube.com/watch?v=B9Ol1Rd9ABI)">little sister.</a>&rdquo; It;&#39;s something I probably wouldn&rsquo;t have thought about before Julian was born, seeing as I have no younger siblings.</p>

<blockquote>
<p>In <a href="http://en.wikipedia.org/wiki/Norse_mythology" title="Norse mythology">Norse mythology</a>, <strong>Nanna Nepsd&oacute;ttir</strong> or simply <strong>Nanna</strong> is a goddess associated with the god <a href="http://en.wikipedia.org/wiki/Baldr" title="Baldr">Baldr</a>. Accounts of Nanna vary greatly by source. In the <em><a href="http://en.wikipedia.org/wiki/Prose_Edda" title="Prose Edda">Prose Edda</a></em>, written in the 13th century by <a href="http://en.wikipedia.org/wiki/Snorri_Sturluson" title="Snorri Sturluson">Snorri Sturluson</a>, Nanna is the wife of Baldr and the couple produced a son, the god <a href="http://en.wikipedia.org/wiki/Forseti" title="Forseti">Forseti</a>. After Baldr&rsquo;s death, Nanna dies of grief. Nanna is placed on Baldr&rsquo;s ship with his corpse and the two are set aflame and pushed out to sea. In <a href="http://en.wikipedia.org/wiki/Hel_(location)" title="Hel (location)">Hel</a>, Baldr and Nanna are united again. In an attempt to bring back Baldr from the dead, the god <a href="http://en.wikipedia.org/wiki/Herm%C3%B3%C3%B0r" title="Hermóðr">Herm&oacute;&eth;r</a> rides to Hel and, upon receiving the hope of resurrection from the being <a href="http://en.wikipedia.org/wiki/Hel_(being)" title="Hel (being)">Hel</a>, Nanna gives Herm&oacute;&eth;r gifts to give to the goddess <a href="http://en.wikipedia.org/wiki/Frigg" title="Frigg">Frigg</a> (a robe of linen), the goddess <a href="http://en.wikipedia.org/wiki/Fulla" title="Fulla">Fulla</a> (a finger-ring), and others (unspecified). Nanna is frequently mentioned in the poetry of <a href="http://en.wikipedia.org/wiki/Skald" title="Skald">skalds</a> and a Nanna, who may or may not be the same figure, is mentioned once in the <em><a href="http://en.wikipedia.org/wiki/Poetic_Edda" title="Poetic Edda">Poetic Edda</a></em>, compiled in the 13th century from earlier traditional sources.</p>

<p><strong>Inanna</strong><a href="http://en.wikipedia.org/wiki/Inanna#cite_note-8">[a]</a> is an <a href="http://en.wikipedia.org/wiki/List_of_Mesopotamian_deities" title="List of Mesopotamian deities">ancient Mesopotamian goddess</a> associated with sex, war, justice, and political power. She was originally worshiped in <a href="http://en.wikipedia.org/wiki/Sumer" title="Sumer">Sumer</a> and was later worshipped by the <a href="http://en.wikipedia.org/wiki/Akkadian_Empire" title="Akkadian Empire">Akkadians</a>, <a href="http://en.wikipedia.org/wiki/Babylonian_religion" title="Babylonian religion">Babylonians</a>, and <a href="http://en.wikipedia.org/wiki/Assyria" title="Assyria">Assyrians</a> under the name <strong>Ishtar</strong>.<a href="http://en.wikipedia.org/wiki/Inanna#cite_note-9">[b]</a> She was known as the &ldquo;<a href="http://en.wikipedia.org/wiki/Queen_of_heaven_(antiquity)" title="Queen of heaven (antiquity)">Queen of Heaven</a>&rdquo; and was the patron goddess of the <a href="http://en.wikipedia.org/wiki/Eanna" title="Eanna">Eanna</a> temple at the city of <a href="http://en.wikipedia.org/wiki/Uruk" title="Uruk">Uruk</a>, which was her main <a href="http://en.wikipedia.org/wiki/Cult_(religious_practice)" title="Cult (religious practice)">cult</a> center. She was associated with the planet <a href="http://en.wikipedia.org/wiki/Venus" title="Venus">Venus</a> and her most prominent symbols included the <a href="http://en.wikipedia.org/wiki/Lion_of_Babylon" title="Lion of Babylon">lion</a> and the <a href="http://en.wikipedia.org/wiki/Star_of_Ishtar" title="Star of Ishtar">eight-pointed star</a>. Her husband was the god <a href="http://en.wikipedia.org/wiki/Dumuzid" title="Dumuzid">Dumuzid</a> (later known as Tammuz) and her <em>sukkal</em>, or personal attendant, was the goddess <a href="http://en.wikipedia.org/wiki/Ninshubur" title="Ninshubur">Ninshubur</a> (who later became the male deity <a href="http://en.wikipedia.org/wiki/Papsukkal" title="Papsukkal">Papsukkal</a>).</p>
</blockquote>

<p>I previously wrote about Nanna, Inanna and Tammuz here: <a href="http://medium.com/in-pursuit-of-happiness/on-the-salted-road-through-the-amduat-317cd4967339?source=collection_archive---------5-----------------------">On the Salted Road thru the Amduat</a></p>

<hr />
<p style="text-align: justify;">When I was a younger boy (than today); I used to comment that &ldquo;all languages lead to Jerusalem&rdquo; &hellip; that was the world I grew up in, it was &hellip; I remember &ldquo;verifying it&rdquo; that in that place Cyrillic and Japanese and Chinese were read right to left, paralleling the hidden Bible Code that I&rsquo;ve based much of my analysis of the Torah and the Koran and &hellip; the Norse Key of Ragnarok on. Here I look, and that doesn&rsquo;t exist at all in our history, I can&rsquo;t tell you to if it included Hindi or cuneiform &hellip; but you would probably imagine that it did. I can&rsquo;t tell you if it was &ldquo;one in the same&rdquo; with seeing Koran written in that direction in English in the word Ragnarok, or if this is some other later places where that was done and undone. I can tell you for sure that I connected this Bible Code from Hebrew4Christians to this &hellip; idea that the idiomatic &ldquo;all roads lead to Rome&rdquo; and the idea that &ldquo;Jerusalem is the city of time&rdquo; and &hellip;</p>

<p style="text-align: center;"><a href="./CONNETICUT.html"><img alt="" src="./i.imgur.com/BkTd1T4.png" /></a></p>

<p style="text-align: center;"><a href="./MISCHADPUCHUH">MISCHADPUCHUH</a> | <a href="./FIRST.html">FIRST</a> | <a href="./CONNETICUT.html">CON NET I C UT</a></p>

<p style="text-align: justify;">I read about &hellip; as a small child that the rabbis that were responsible for transcribing the Torah had found &hellip; &ldquo;an error&rdquo; one that they together decided was &ldquo;intentionally made by God&rdquo; &hellip; I recall it being something very small, something like the &ldquo;past imperfect tense&rdquo; being used in one of &ldquo;his many names.&rdquo; Today that&rsquo;s just not the case; I look around and there&rsquo;s an entirely new &hellip; set of errors. Names of major books appear to me have been changed. <a href="http://en.wikipedia.org/wiki/Torah%5D(http://en.wikipedia.org/wiki/Torah)">Bernidbar &hellip; the book of Numbers now connects to Jesus&rsquo; manger</a>, &ldquo;styrofoam&rdquo; and thirsty&ndash;it also links to Bernie Sanders and to my grandfathers first name; something I would have noticed, and remembered. Leviticus&rsquo; Hebrew name reminds of Valkyrie&ndash;something else I probably would have noticed. Most importantly, the entirety of the &ldquo;broken Vav&rdquo; in Leviticus &hellip; it appears to be a &ldquo;grave error&rdquo; one that at least the scribes would have noticed; and I recall nearly perfectly reading about that particular event. Things are changing, and it&rsquo;s not a good thing that we don&rsquo;t have a documented history&ndash;either that or I&rsquo;m really from &hellip; another world, and that too would be quite scary for me &hellip; to &ldquo;wake up&rdquo; in a new place made with &hellip; grave mistakes.</p>

<p style="text-align: justify;">Of course it&rsquo;s &ldquo;s-typical&rdquo; of the pig-sty I&rsquo;ve come to know&ndash;a place where we have little regard for &hellip; things like history and continuity of reality&ndash;numerous stories I&rsquo;ve walked through, literally discussing nothing less tragic and grave than a mass disregard for the need to have &hellip; &ldquo;plausible historical causality&rdquo; as in, &ldquo;well, we know the broken vav didn&rsquo;t happen until at least the first time &lsquo;I came&rsquo;&rdquo; and we <a href="http://reck.reallyhim.com">know</a> in <a href="./MYLIFE.html">my life</a> that ties to a causal and historical marker, a car accident in November 2001 that probably resulted in my death or Lazarus&rsquo; physical incapacitation in a past or divergent timeline. I stand here reading &hellip; a timeline of the blood of Jesus Christ, one that connects to Adam in Eden and Abraham in Ur; and it ties through divergence in Ishmael and Isaac (of course I identify with all four of those character) as well as Saul, Paul and David; all the way to Joseph in Egypt (whose coat and dream I <a href="http://www.myjewishlearning.com/torah-portions/parashat-vayeshev/%5D(http://www.myjewishlearning.com/torah-portions/parashat-vayeshev/)">read and spoke about for my Hafterah</a> (sic)); and his link to Josephus, Joseph the father of Christ and &hellip; his paul-bearer, <a href="./CKIMPER.html">Joseph of Arimathea</a>.</p>

<p style="text-align: justify;">Of course &hellip; I literally believe myself to be &ldquo;living the life of the first Joseph&rdquo; sold &ldquo;into slavery&rdquo; to write this message for &hellip; basically nothing &hellip; by his brothers&ndash;here &ldquo;alternate Adams&rdquo; and <a href="./ADAMSROD.html">dreaming literally breathing Heaven into exist</a>ence through &hellip; well, I suppose through you :/.</p>

<p style="text-align: center;"><img alt="Are Dolphins Smarter Than You? | Planet Pailly" src="http://planetpailly.files.wordpress.com/2011/10/darwin-the-dolphin.jpg" /></p>

<h2 id="flipper-sea-quest-and-...-hey-carlos--are-you-there">Flipper, Sea Quest and &hellip; hey, Carlos? Are you there?</h2>

<p style="text-align: justify;">In the beginning of &ldquo;my story here&rdquo; &hellip; the phrase &ldquo;7 people&rdquo; didn&rsquo;t mean the same thing it means today&ndash;once a long time ago it meant the union of two species, something like the comparable Martian and Earthling joinder you would have gotten by adding those planets index from the sun &hellip; 3 and 4 together &hellip; and that mean that kind of union, working together, that was the &ldquo;beginning of Heaven.&rdquo;</p>

<blockquote>
<p>join&middot;der</p>

<p>/ˈjoindər/ <em>noun</em></p>

<p>LAW TERM</p>

<ol>
	<li>the action of bringing parties together; union.</li>
</ol>

<p>&ldquo;the joinder of parties&rdquo;</p>
</blockquote>

<p style="text-align: justify;">Today it means &hellip; &ldquo;not 8&rdquo; in my lexicon, or Adamic; or the common usage that I hear the people around me using; something like &ldquo;ignoring&rdquo; &hellip; or not &ldquo;knowing my name&rdquo; &hellip; and that&rsquo;s probably a temporary fleeting kind of meaning, it seems like it&rsquo;s been erased from existence by another force, or maybe through these messages and a kind of communication and diffusion in another place, perhaps what you consider Heaven today, that I do not see or understand. Regardless, I think as we struggle with food shortage and lack of &ldquo;social togetherness&rdquo; here in these coming weeks that we take special time to think about what it means to live in a &ldquo;Zu&rdquo; or a &ldquo;Zoo&rdquo; ,&hellip; what it means to be in the spotlight and <a href="http://www.youtube.com/watch?v=clKAdQnwJ7A%5D(http://www.youtube.com/watch?v=clKAdQnwJ7A)">what it means to really &ldquo;shine.&rdquo;</a></p>

<p style="text-align: center;"><a href="http://www.hebrew4christians.com/Grammar/Unit_One/Aleph-Bet/Vav/vav.html%5D(http://www.hebrew4christians.com/Grammar/Unit_One/Aleph-Bet/Vav/vav.html)"><img alt="" src="./i.imgur.com/b6KAOX3.png" style="height: 347px; width: 500px;" /></a></p>

<p style="text-align: justify;">This is &ldquo;original work&rdquo; &hellip; nearly everything I write about is sourced from some kind of external source, an &ldquo;idea&rdquo; someone else had, that I connected with another idea, and another group of people&ndash;sometimes a band or a cast from a movie or a group of authors or maybe even sometimes just one. The majority of my work is uncited, though I link back to original sources in the &ldquo;GNU style&rdquo; of showing you how that gives those authors and those people an additional voice, an ability to &ldquo;add to what I&rsquo;ve said&rdquo; in a way that most people &hellip; most people haven&rsquo;t been afforded as of yet. Once, a long time ago I had a commenting system that allowed people to directly edit or comment on this writing as I was writing it, it was nearly instantly removed by forces outside myself, and today&ndash;seeing the lack of commenting in other places and the general &ldquo;air&rdquo; of not being happy with anything I&rsquo;ve written&ndash;I&rsquo;m almost happy that nobody else helped write a single one of these words. You&rsquo;re attitude is wrong, your analysis is wrong; and you simply do not understand the amount of work or the</p>

<h2 id="flipper-jce-coiture...-dsv">FLIPPER, JCE COITURE&hellip; DSV</h2>

<p style="text-align: justify;">There&rsquo;s plenty of fiction about it &hellip; talking dolphins in the SeaQuest TV series&ndash;and whales that save humanity from an alien invasion &hellip; in the Star Trek movie, &ldquo;The Voyage Home.&rdquo; Here we are, finally &ldquo;[not talking about it again&rdquo; (hello darkness], the bane of my existence) and it&rsquo;s almost as if you really think the humans you see around you every day are absolutely worthless. Literally the founders and creators of Heaven&ndash;it appears very much to me like I am staring at a hidden alien invasion of our minds &hellip; even sometimes by something that may have come directly from this place, and you&rsquo;ve simply just decidekd that all of our history, and everything that we are &hellip; right down to &ldquo;Americana itself&rdquo; &hellip; is simply below you. You are in for a rude awakening.</p>

<p style="text-align: justify;">I stare around me at monsters, cannibals, literally a group &hellip; a gigantic conspiracy of torturers; attempting to destroy me and this message, and with it the whole of the future&ndash;using disgusting psychological torture and threats &hellip; through a communication mechanism that is literally torture in and of itself. You, nobody has a right to &ldquo;view what&rsquo;s going on inside your head&rdquo; &hellip; and especially to use it to create psychological damage&ndash;which is all you have become in my mind in these last days, even those of you that do nothing more than &ldquo;sit back and watch.&rdquo; We here, humanity&ndash;we have a God given right to privacy, and even though we have spoken numerous occasions (myself, and Senator Wyden, for instance) about how technology might change how we deal with things like &ldquo;technological privacy&rdquo; &ndash; the disgusting invasion of my fourth amendment <em>right;</em> en masse here is nothing short of &hellip; it&rsquo;s beyond tragedy&ndash;it literally appears to be the end of the Constitution, the United States, Heaven, and with those things &ldquo;the future of civilization.&rdquo;</p>

<p style="text-align: justify;">This is the actual &ldquo;meaning and purpose&rdquo; of Jewish Kosher law; to ensure that the animals we eat are humanely slaughtered&ndash;the specific connection to &ldquo;pigs flying&rdquo; here, not just to David and the Parkland shooting &hellip; but also to Kill Devil Hills and the complete lack of any sane discussion about &ldquo;Heaven&rdquo; and &ldquo;Doors&rdquo; &hellip; in this place where the &ldquo;gravity of the situation&rdquo; clearly hasn&rsquo;t clipped your wings yet. I don&rsquo;t think you have a prayer, or a chance in Hell; to be honest. I really don&rsquo;t.</p>

<p style="text-align: justify;">You have come this far, and descended &hellip; to lows and pits I cannot even fathom; with a sickness that has nothing to do with SARS or &ldquo;human engineered viruses&rdquo; &hellip;</p>

<p style="text-align: justify;">the thing this world is ignoring is far too big and far too sick to go unnoticed or be &ldquo;sweeped under a rug.&rdquo; This is really your last chance, I suggest you seize the opportunity to &ldquo;change my mind.&rdquo; As in today. Now.</p>

<hr />
<p style="text-align: justify;">For what it&rsquo;s worth, I&rsquo;ve commented about the American Indian societies&rsquo; similarity to Kosher law, to utilize as much of dead animals as possible and to minimize killing&ndash;I think there&rsquo;s a clear link here between Native Americans and the Indians of the Far East Silk Road&ndash;one that ties to Halal and probably should very much add &ldquo;cows&rdquo; and mammals to the list of animals that are &ldquo;simply too intelligent&rdquo; to be farmed and zooed into &ldquo;human like prisons&rdquo; for feeding. Of course, you still have prisons for yourselves; and that&rsquo;s really the crux of the problem.</p>

<p style="text-align: center;">Good luck.<br />
<br />
<a href="http://en.wikipedia.org/wiki/Project_Daedalus%5D(http://en.wikipedia.org/wiki/Project_Daedalus)"><img alt="" src="./i.imgur.com/xoOnizg.png" style="height: 174px; width: 500px;" /></a></p>

<blockquote>
<p><strong>Project Daedalus</strong> was a study conducted between 1973 and 1978 by the <a href="http://en.wikipedia.org/wiki/British_Interplanetary_Society" title="British Interplanetary Society">British Interplanetary Society</a> to design a plausible <a href="http://en.wikipedia.org/wiki/Uncrewed_spacecraft" title="Uncrewed spacecraft">uncrewed</a> <a href="http://en.wikipedia.org/wiki/Interstellar_spacecraft" title="Interstellar spacecraft">interstellar spacecraft</a>.<a href="http://en.wikipedia.org/wiki/Project_Daedalus#cite_note-study-1">[1]</a> Intended mainly as a scientific probe, the design criteria specified that the spacecraft had to use existing or near-future technology and had to be able to reach its destination within a human lifetime. <a href="http://en.wikipedia.org/wiki/Alan_Bond_(engineer)" title="Alan Bond (engineer)">Alan Bond</a> led a team of scientists and engineers who proposed using a <a href="http://en.wikipedia.org/wiki/Fusion_rocket" title="Fusion rocket">fusion rocket</a> to reach <a href="http://en.wikipedia.org/wiki/Barnard%27s_Star" title="Barnard's Star">Barnard&rsquo;s Star</a> 5.9 <a href="http://en.wikipedia.org/wiki/Light_year" title="Light year">light years</a> away. The trip was estimated to take 50 years, but the design was required to be flexible enough that it could be sent to any other target star.</p>
</blockquote>

<p style="text-align: center;">[[ cue more ominous foreshadowing ]]</p>

<p style="text-align: justify;">FWIW, I&rsquo;ve stopped eating pork and beef. I suggest you &hellip; do some research into &ldquo;lab grown&rdquo; alternatives; and see how it might go and in hand with our &ldquo;current look at what a world without transportation, farming, or food supply&rdquo; might look like&ndash;there&rsquo;s good practical as well as ethical reason.</p>

<p style="text-align: center;"><a href="http://www.theguardian.com/environment/2018/dec/14/worlds-first-lab-grown-beef-steak-revealed-but-the-taste-needs-work"><img alt="" src="./i.imgur.com/CwF1ha2.png" style="height: 350px; width: 500px;" /></a></p>

<p>&hellip; and &ldquo;Snoop on same or similar.&rdquo; (who is apparently now a blonde)</p>

<p style="text-align: center;"><img alt="" src="./i.imgur.com/kt1K1xz.png" style="height: 253px; width: 400px;" /></p>

<h2 id="ragnarok-koran-gard-...">RAGNAROK, KORAN-GARD &hellip;</h2>

<p><br />
<a href="http://biblehub.com/interlinear/joshua/2.htm%5D(http://biblehub.com/interlinear/joshua/2.htm)"><img alt="" src="./i.imgur.com/VH7T4vT.png" /></a></p>

<p>&nbsp;</p>
</div>

